<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Business Economic and Financial Data Project</title>

<script src="FINAL_CODE_NEW_files/header-attrs-2.29/header-attrs.js"></script>
<script src="FINAL_CODE_NEW_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="FINAL_CODE_NEW_files/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="FINAL_CODE_NEW_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="FINAL_CODE_NEW_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="FINAL_CODE_NEW_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="FINAL_CODE_NEW_files/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="FINAL_CODE_NEW_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="FINAL_CODE_NEW_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="FINAL_CODE_NEW_files/navigation-1.1/tabsets.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div id="header">



<h1 class="title toc-ignore">Business Economic and Financial Data
Project</h1>

</div>


<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-8"><a href="#cb1-8" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-9"><a href="#cb1-9" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb1-10"><a href="#cb1-10" tabindex="-1"></a><span class="fu">library</span>(mgcv)</span>
<span id="cb1-11"><a href="#cb1-11" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb1-12"><a href="#cb1-12" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb1-13"><a href="#cb1-13" tabindex="-1"></a><span class="fu">library</span>(prophet)</span>
<span id="cb1-14"><a href="#cb1-14" tabindex="-1"></a><span class="fu">library</span>(gam)</span>
<span id="cb1-15"><a href="#cb1-15" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-16"><a href="#cb1-16" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;Code/Functions_Utilies.R&quot;</span>)</span></code></pre></div>
<div id="data-loading-and-preprocessing" class="section level1">
<h1>Data Loading and Preprocessing</h1>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;Data/data.csv&quot;</span>)</span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a>data<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(data<span class="sc">$</span>Date, <span class="at">format =</span> <span class="st">&quot;%Y-%m-%d&quot;</span>) <span class="co"># ensure date format</span></span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Month =</span> <span class="fu">format</span>(Date, <span class="st">&quot;%m&quot;</span>),</span>
<span id="cb2-4"><a href="#cb2-4" tabindex="-1"></a>                        <span class="at">Year =</span> <span class="fu">as.factor</span>(<span class="fu">format</span>(Date, <span class="st">&quot;%Y&quot;</span>))) <span class="co"># create useful features for the models</span></span>
<span id="cb2-5"><a href="#cb2-5" tabindex="-1"></a>data<span class="sc">$</span>trend <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data)</span>
<span id="cb2-6"><a href="#cb2-6" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" tabindex="-1"></a><span class="fu">head</span>(data,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 6
##   Date       Baccala_Mantecato Baccala_Vicentina Month Year  trend
##   &lt;date&gt;                 &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt; &lt;fct&gt; &lt;int&gt;
## 1 2021-01-01              36.4               6.1 01    2021      1
## 2 2021-02-01              36.4               5.4 02    2021      2
## 3 2021-03-01              31.2               6.1 03    2021      3</code></pre>
<p>Check for missing values</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(data))</span></code></pre></div>
<pre><code>##              Date Baccala_Mantecato Baccala_Vicentina             Month 
##                 0                 0                 0                 0 
##              Year             trend 
##                 0                 0</code></pre>
<p>Then we load a dataset found on <a
href="https://eumofa.eu/web/guest/bulk-download">EUMOFA</a>. We also
tried incorporating different variables, such as the NIC for fish
products (Istat), the production price of fish products (Istat), and
others. However, these variables did not prove to be significantly
relevant for our analysis. Additionally, some other variables we tried
do not have monthly data that match the frequency of the sales data we
are working with, limiting their usefulness in the context of our time
series analysis.</p>
<p>Here we focus on the salmon consumption only because we have seen
that other fishes or their aggregate value lead worst results.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a>fish_cons <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;Data/Fish_consumption_ita_raw.xlsx&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>  <span class="fu">filter</span>(CG <span class="sc">==</span> <span class="st">&quot;Salmon&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">kg =</span> <span class="fu">as.numeric</span>(<span class="st">`</span><span class="at">volume(Kg)</span><span class="st">`</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a>  <span class="fu">group_by</span>(year, month) <span class="sc">%&gt;%</span></span>
<span id="cb6-5"><a href="#cb6-5" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">kg =</span> <span class="fu">sum</span>(kg), <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-6"><a href="#cb6-6" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&gt;</span> <span class="dv">2020</span> <span class="sc">|</span> (year <span class="sc">==</span> <span class="dv">2020</span> <span class="sc">&amp;</span> month <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">12</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb6-7"><a href="#cb6-7" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-8"><a href="#cb6-8" tabindex="-1"></a>    <span class="at">kg_std =</span> <span class="fu">scale</span>(kg),</span>
<span id="cb6-9"><a href="#cb6-9" tabindex="-1"></a>    <span class="at">Date =</span> <span class="fu">as.Date</span>(<span class="fu">paste</span>(year, month, <span class="st">&quot;01&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;-&quot;</span>))</span>
<span id="cb6-10"><a href="#cb6-10" tabindex="-1"></a>  )  <span class="sc">%&gt;%</span></span>
<span id="cb6-11"><a href="#cb6-11" tabindex="-1"></a>  <span class="fu">select</span>(Date, kg, kg_std)</span>
<span id="cb6-12"><a href="#cb6-12" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" tabindex="-1"></a><span class="fu">head</span>(fish_cons, <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   Date             kg kg_std[,1]
##   &lt;date&gt;        &lt;dbl&gt;      &lt;dbl&gt;
## 1 2020-11-01 1943824.      0.890
## 2 2020-12-01 2850563       2.74 
## 3 2021-01-01 1803247       0.603</code></pre>
<p>The dataset contains three columns:</p>
<p>Date: Unlike the data related to baccalà, the time series for salmon
starts from November 2020. This is because we lack information for the
last two months of 2024, so we applied a two-month lag. This choice also
makes sense for future applications, as it would not be possible to
forecast baccalà sales (whether mantecato or alla vicentina) for
December when monthly consumption data for that month is already
available.</p>
<p>kg_std: Represents the standardized version of the kg column. Since
the values in kg are quite large, we opted to standardize them to
simplify further analysis.</p>
<p>kg: Represents the quantity of salmon sold in Italy, measured in
kilograms.</p>
<p>Finally we aggregate the salmon monthly consumption time series to
our data.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a>data<span class="sc">$</span>fish_cons <span class="ot">&lt;-</span> fish_cons<span class="sc">$</span>kg_std[,<span class="dv">1</span>]</span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a><span class="fu">head</span>(data,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 7
##   Date       Baccala_Mantecato Baccala_Vicentina Month Year  trend fish_cons
##   &lt;date&gt;                 &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt; &lt;fct&gt; &lt;int&gt;     &lt;dbl&gt;
## 1 2021-01-01              36.4               6.1 01    2021      1     0.890
## 2 2021-02-01              36.4               5.4 02    2021      2     2.74 
## 3 2021-03-01              31.2               6.1 03    2021      3     0.603</code></pre>
</div>
<div id="explanatory-analysis" class="section level1">
<h1>Explanatory Analysis</h1>
<p>First, we visualize the time series of Baccala Mantecato and Baccala
Vicentina over time. This plot helps us compare the trend of sales for
both products on a monthly basis.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Date)) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Baccala_Mantecato, <span class="at">color =</span> <span class="st">&quot;Baccala Mantecato&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Baccala_Vicentina, <span class="at">color =</span> <span class="st">&quot;Baccala Vicentina&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Monthly Time Series of Baccala Mantecato and Baccala Vicentina&quot;</span>,</span>
<span id="cb10-5"><a href="#cb10-5" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb10-6"><a href="#cb10-6" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Quantity&quot;</span>) <span class="sc">+</span></span>
<span id="cb10-7"><a href="#cb10-7" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Baccala Mantecato&quot;</span> <span class="ot">=</span> <span class="st">&quot;#FF7F7F&quot;</span>, <span class="st">&quot;Baccala Vicentina&quot;</span> <span class="ot">=</span> <span class="st">&quot;#6BC3FF&quot;</span>)) <span class="sc">+</span></span>
<span id="cb10-8"><a href="#cb10-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb10-9"><a href="#cb10-9" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/exploratory_baccala_analysis-1.png" width="768" /></p>
<p>The sales quantities of Baccala Mantecato and Baccala Vicentina show
significant differences, with Baccala Mantecato consistently having a
much higher volume of sales throughout all periods observed.
Additionally, Baccala Mantecato exhibits a much wider range of values,
indicating greater variability in sales. In contrast, Baccala Vicentina
appears more stable, with sales peaks typically occurring towards the
end of the year. A similar trend is also seen for Baccala Mantecato,
which experiences an uptick in sales during the final months of each
year.</p>
<p>Next, we plot the time series for both products grouped by year. The
goal is to observe yearly trends and patterns for Baccala Mantecato and
Baccala Vicentina separately.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> Baccala_Mantecato, <span class="at">color =</span> Year, <span class="at">group =</span> Year)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Month&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Baccala Mantecato&quot;</span>, </span>
<span id="cb11-4"><a href="#cb11-4" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Monthly Time Series of Baccala Mantecato by Year&quot;</span>) <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span>
<span id="cb11-7"><a href="#cb11-7" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> Baccala_Vicentina, <span class="at">color =</span> Year, <span class="at">group =</span> Year)) <span class="sc">+</span></span>
<span id="cb11-9"><a href="#cb11-9" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb11-10"><a href="#cb11-10" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Month&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Baccala Vicentina&quot;</span>, </span>
<span id="cb11-11"><a href="#cb11-11" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Monthly Time Series of Baccala Vicentina by Year&quot;</span>) <span class="sc">+</span></span>
<span id="cb11-12"><a href="#cb11-12" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb11-13"><a href="#cb11-13" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span>
<span id="cb11-14"><a href="#cb11-14" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" tabindex="-1"></a><span class="fu">grid.arrange</span>(plot1, plot2, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/yearly_trends_baccala_sales-1.png" width="768" /></p>
<p>Both graphs highlight the pattern mentioned earlier: for each year,
there is an increase in sales during the final months of the year,
particularly in September and December. Additionally, regarding Baccala
Mantecato, it appears that during the earlier years of sales for which
we have data, the quantity sold was generally higher in the off-peak
months (for example, the orange line for 2021 is higher compared to the
other years). However, in the later years, the quantity sold during the
peak months has increased.</p>
<p>Finally, we also examined the properties of the time series by
plotting the autocorrelation functions (ACF).</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a>ym <span class="ot">=</span> <span class="fu">ts</span>(data<span class="sc">$</span>Baccala_Mantecato, <span class="at">frequency =</span> <span class="dv">12</span>, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">2021</span>, <span class="dv">1</span>))</span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>yv <span class="ot">=</span> <span class="fu">ts</span>(data<span class="sc">$</span>Baccala_Vicentina, <span class="at">frequency =</span> <span class="dv">12</span>, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">2021</span>, <span class="dv">1</span>))</span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">end</span>(ym)[<span class="dv">1</span>] <span class="sc">!=</span> <span class="dv">2024</span> <span class="sc">||</span> <span class="fu">end</span>(ym)[<span class="dv">2</span>] <span class="sc">!=</span> <span class="dv">12</span>) {</span>
<span id="cb12-5"><a href="#cb12-5" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;Error in ts ym&quot;</span>)</span>
<span id="cb12-6"><a href="#cb12-6" tabindex="-1"></a>}</span>
<span id="cb12-7"><a href="#cb12-7" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">end</span>(yv)[<span class="dv">1</span>] <span class="sc">!=</span> <span class="dv">2024</span> <span class="sc">||</span> <span class="fu">end</span>(yv)[<span class="dv">2</span>] <span class="sc">!=</span> <span class="dv">12</span>) {</span>
<span id="cb12-8"><a href="#cb12-8" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;Error in ts yv&quot;</span>)</span>
<span id="cb12-9"><a href="#cb12-9" tabindex="-1"></a>}</span>
<span id="cb12-10"><a href="#cb12-10" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" tabindex="-1"></a><span class="fu">tsdisplay</span>(data<span class="sc">$</span>Baccala_Mantecato)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/acf_pacf_analysis-1.png" width="768" /></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a><span class="fu">tsdisplay</span>(data<span class="sc">$</span>Baccala_Vicentina)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/acf_pacf_analysis-2.png" width="768" /></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a><span class="co">#Acf(data$Baccala_Mantecato, main = &quot;ACF of Baccala Mantecato&quot;, col = &quot;#FF7F7F&quot;, lwd = 2)</span></span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a><span class="co">#Pcf(data$Baccala_Mantecato, main = &quot;PACF of Baccala Mantecato&quot;, col = &quot;#FF7F7F&quot;, lwd = 2)</span></span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a><span class="co">#Acf(data$Baccala_Vicentina, main = &quot;ACF of Baccala Vicentina&quot;, col = &quot;#6BC3FF&quot;, lwd = 2)</span></span>
<span id="cb14-4"><a href="#cb14-4" tabindex="-1"></a><span class="co">#Pacf(data$Baccala_Vicentina, main = &quot;PACF of Baccala Vicentina&quot;, col = &quot;#6BC3FF&quot;, lwd = 2)</span></span></code></pre></div>
<p>We now that autocorrelation occurs when the effect of a avriable is
spread over time, in these cases, most of the autocorrelations fall
within the confidence bands, indicating that the data does not show
significant correlation for most lags. However, within the bands, the
autocorrelations exhibit a sinusoidal pattern, suggesting the presence
of seasonality in the data, where periodic fluctuations occur over time.
The peak at lag 12 further supports the idea of a cyclical effect. We
will analyze the residuals of future models to confirm or disprove the
presence of this seasonality.</p>
</div>
<div id="train-test-split" class="section level1">
<h1>Train &amp; Test Split</h1>
<p>In this section, we perform a train-test split to prepare the data
for model training and evaluation. We divide the time series data for
both Baccala Mantecato and Baccala Vicentina into training and testing
sets, with 90% of the data allocated for training and the remaining 10%
for testing.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a>prop <span class="ot">&lt;-</span> <span class="fl">0.8</span></span>
<span id="cb15-2"><a href="#cb15-2" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" tabindex="-1"></a>n_sample <span class="ot">&lt;-</span> <span class="fu">floor</span>(<span class="fu">nrow</span>(data) <span class="sc">*</span> prop)</span>
<span id="cb15-4"><a href="#cb15-4" tabindex="-1"></a>  </span>
<span id="cb15-5"><a href="#cb15-5" tabindex="-1"></a>train <span class="ot">&lt;-</span> data[<span class="dv">1</span><span class="sc">:</span>n_sample, ]</span>
<span id="cb15-6"><a href="#cb15-6" tabindex="-1"></a>y_trainm <span class="ot">&lt;-</span> train[[<span class="st">&quot;Baccala_Mantecato&quot;</span>]]</span>
<span id="cb15-7"><a href="#cb15-7" tabindex="-1"></a>y_trainv <span class="ot">&lt;-</span> train[[<span class="st">&quot;Baccala_Vicentina&quot;</span>]]</span>
<span id="cb15-8"><a href="#cb15-8" tabindex="-1"></a>  </span>
<span id="cb15-9"><a href="#cb15-9" tabindex="-1"></a>test <span class="ot">&lt;-</span> data[(n_sample <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span><span class="fu">nrow</span>(data), ]</span>
<span id="cb15-10"><a href="#cb15-10" tabindex="-1"></a>  </span>
<span id="cb15-11"><a href="#cb15-11" tabindex="-1"></a>y_testm <span class="ot">&lt;-</span> test[[<span class="st">&quot;Baccala_Mantecato&quot;</span>]]</span>
<span id="cb15-12"><a href="#cb15-12" tabindex="-1"></a>y_testv <span class="ot">&lt;-</span> test[[<span class="st">&quot;Baccala_Vicentina&quot;</span>]]</span></code></pre></div>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a>Type <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;Train&quot;</span>, <span class="fu">dim</span>(train)[<span class="dv">1</span>]), <span class="fu">rep</span>(<span class="st">&quot;Test&quot;</span>, <span class="fu">dim</span>(test)[<span class="dv">1</span>]))</span>
<span id="cb16-2"><a href="#cb16-2" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> trend, <span class="at">y =</span> Baccala_Mantecato, <span class="at">color =</span> Type)) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;#FF7F7F&quot;</span>, <span class="st">&quot;#6BC3FF&quot;</span>)) <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Train and Test Data for Baccala Mantecato&quot;</span>,</span>
<span id="cb16-6"><a href="#cb16-6" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Time&quot;</span>,</span>
<span id="cb16-7"><a href="#cb16-7" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Quantity sold of Baccala Mantecato&quot;</span>) <span class="sc">+</span></span>
<span id="cb16-8"><a href="#cb16-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/train_test_visualization-1.png" width="768" /></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> trend, <span class="at">y =</span> Baccala_Vicentina, <span class="at">color =</span> Type)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;#FF7F7F&quot;</span>, <span class="st">&quot;#6BC3FF&quot;</span>)) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Train and Test Data for Baccala Vicentina&quot;</span>,</span>
<span id="cb17-5"><a href="#cb17-5" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Time&quot;</span>,</span>
<span id="cb17-6"><a href="#cb17-6" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Quantity sold of Baccala Vicentina&quot;</span>) <span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb17-8"><a href="#cb17-8" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/train_test_visualization-2.png" width="768" /></p>
</div>
<div id="modelling-phase" class="section level1">
<h1>Modelling Phase</h1>
<div id="linear-regression-model" class="section level2">
<h2>Linear Regression Model</h2>
<div id="baccala-mantecato" class="section level3">
<h3>Baccala Mantecato</h3>
<p>We start by estimating a simple linear regression model with all the
possible variables</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a>lr_m <span class="ot">&lt;-</span> <span class="fu">lm</span>(Baccala_Mantecato <span class="sc">~</span> trend <span class="sc">+</span> Month <span class="sc">+</span> fish_cons, <span class="at">data =</span> train)</span>
<span id="cb18-2"><a href="#cb18-2" tabindex="-1"></a><span class="fu">summary</span>(lr_m)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Baccala_Mantecato ~ trend + Month + fish_cons, data = train)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.7655 -1.9233 -0.1261  1.5838  5.2790 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  28.76483    2.33754  12.306 7.41e-12 ***
## trend         0.17966    0.07826   2.296 0.030739 *  
## Month02     -12.02497    3.23351  -3.719 0.001069 ** 
## Month03      -2.76863    2.52651  -1.096 0.284028    
## Month04      -3.83513    2.51453  -1.525 0.140284    
## Month05       3.59937    2.50358   1.438 0.163434    
## Month06      -3.31292    2.63052  -1.259 0.219991    
## Month07       2.11136    2.84382   0.742 0.465027    
## Month08      -7.16741    2.58442  -2.773 0.010563 *  
## Month09       7.26070    2.67281   2.717 0.012042 *  
## Month10     -10.51947    2.64547  -3.976 0.000559 ***
## Month11      -3.59240    2.82306  -1.273 0.215379    
## Month12      14.82343    2.55508   5.802 5.56e-06 ***
## fish_cons     7.79469    1.31187   5.942 3.93e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.275 on 24 degrees of freedom
## Multiple R-squared:  0.9178, Adjusted R-squared:  0.8732 
## F-statistic: 20.61 on 13 and 24 DF,  p-value: 6.729e-10</code></pre>
<p>The Multiple R-squared value of 0.9178 indicates that approximately
91.78% of the variability in Baccala_Mantecato is explained by the
model. Then we take a closer look to the coefficents: - the trend
variable has a positive coefficient of 0.18, meaning that, on average,
Baccala_Mantecato increases by 0.18 units for each time period, assuming
all other factors remain constant. -The coefficient for fish_cons is
7.79, indicating a strong positive relationship. Specifically, for each
unit increase in fish consumption, Baccala_Mantecato rises by
approximately 7.79 units. In particular we will provide an exemple: if
the fish consumption in Italy increases by a unit in October 2021, then
keeping all the other variables fixed, the quantity sold in December
2021 will increase of 7.79 kg. - Regarding the Month variables, they
capture seasonal effects by representing deviations from the baseline
month (January). Some months show statistically significant effects
(e.g., February, August, September, October, and December. For example,
December shows a substantial positive effect, indicating a peak in that
month, while months like February and October have negative
coefficients, reflecting significant declines compared to January.</p>
<p>Now we try removing variables to evaluate their impact on model
performance using AIC and adjusted R² values.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="co">#lr_m_&lt;missing_variable&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" tabindex="-1"></a>lr_m_month <span class="ot">&lt;-</span> <span class="fu">lm</span>(Baccala_Mantecato <span class="sc">~</span> trend <span class="sc">+</span> fish_cons, <span class="at">data =</span> train)</span>
<span id="cb20-3"><a href="#cb20-3" tabindex="-1"></a>lr_m_trend <span class="ot">&lt;-</span> <span class="fu">lm</span>(Baccala_Mantecato <span class="sc">~</span> Month <span class="sc">+</span> fish_cons, <span class="at">data =</span> train)</span>
<span id="cb20-4"><a href="#cb20-4" tabindex="-1"></a>lr_m_fish_cons <span class="ot">&lt;-</span> <span class="fu">lm</span>(Baccala_Mantecato <span class="sc">~</span> trend <span class="sc">+</span> Month, <span class="at">data =</span> train)</span>
<span id="cb20-5"><a href="#cb20-5" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Model with trend and fish consumption:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Model with trend and fish consumption:</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  AIC:&quot;</span>, <span class="fu">AIC</span>(lr_m_month), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>##   AIC: 268.4855</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  Adjusted R²:&quot;</span>, <span class="fu">summary</span>(lr_m_month)<span class="sc">$</span>adj.r.squared, <span class="st">&quot;</span><span class="sc">\n\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>##   Adjusted R²: 0.2875235</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Model with trend and month:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Model with trend and month:</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  AIC:&quot;</span>, <span class="fu">AIC</span>(lr_m_fish_cons), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>##   AIC: 242.9203</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  Adjusted R²:&quot;</span>, <span class="fu">summary</span>(lr_m_fish_cons)<span class="sc">$</span>adj.r.squared, <span class="st">&quot;</span><span class="sc">\n\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>##   Adjusted R²: 0.6992935</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Model with month and fish consumption:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Model with month and fish consumption:</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  AIC:&quot;</span>, <span class="fu">AIC</span>(lr_m_trend), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>##   AIC: 216.0883</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  Adjusted R²:&quot;</span>, <span class="fu">summary</span>(lr_m_trend)<span class="sc">$</span>adj.r.squared, <span class="st">&quot;</span><span class="sc">\n\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>##   Adjusted R²: 0.8515828</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Full model:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Full model:</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  AIC:&quot;</span>, <span class="fu">AIC</span>(lr_m), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>##   AIC: 210.5452</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  Adjusted R²:&quot;</span>, <span class="fu">summary</span>(lr_m)<span class="sc">$</span>adj.r.squared, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>##   Adjusted R²: 0.8732335</code></pre>
<p>As we can expect by the summary of the full model, from the AIC and
Adjusted R² results we clearly see that the best model fit belong to the
full model with all predictors: trend, monthly seasonality and fish
consumption.</p>
<p>Finally we will analyze the residuals.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" tabindex="-1"></a>resid_lr <span class="ot">&lt;-</span> <span class="fu">residuals</span>(lr_m)</span>
<span id="cb44-2"><a href="#cb44-2" tabindex="-1"></a>mse_train_lrm <span class="ot">&lt;-</span> <span class="fu">mean</span>(resid_lr<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb44-3"><a href="#cb44-3" tabindex="-1"></a><span class="co">#checkresiduals(lr_m)</span></span>
<span id="cb44-4"><a href="#cb44-4" tabindex="-1"></a><span class="fu">tsdisplay</span>(resid_lr)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/residual_analysis_baccala_mantecato-1.png" width="768" /></p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" tabindex="-1"></a><span class="fu">dwtest</span>(lr_m)</span></code></pre></div>
<pre><code>## 
##  Durbin-Watson test
## 
## data:  lr_m
## DW = 1.3979, p-value = 0.03549
## alternative hypothesis: true autocorrelation is greater than 0</code></pre>
<p>When we analyze the residuals of the linear regression model, as
shown in the plot below, we observe no particular patterns. The
residuals appear to be randomly scattered, indicating that the model has
appropriately captured the underlying trends in the data. This suggests
that the assumptions of linearity, constant variance, and independence
are reasonably satisfied, and the model’s fit is adequate for
forecasting purposes. We also perform the Durbin-Watson test, that is
used to check for autocorrelation in the residuals of a regression
model. Since the p-value is smaller than the significance level (0.05),
we don’t reject the null hypothesis that the autocorrelation of the
disturbances is 0.</p>
<p>Finally we plot the predicted values and the actual ones. We also
compute the MSE on the test set.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb47-2"><a href="#cb47-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> data<span class="sc">$</span>Date, <span class="at">y =</span> data<span class="sc">$</span>Baccala_Mantecato, <span class="at">color =</span> <span class="st">&quot;Actual Values&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb47-3"><a href="#cb47-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> train<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">fitted</span>(lr_m), <span class="at">color =</span> <span class="st">&quot;Fitted Values (Train)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb47-4"><a href="#cb47-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> test<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">predict</span>(lr_m, <span class="at">newdata =</span> test), <span class="at">color =</span> <span class="st">&quot;Predicted Values (Test)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb47-5"><a href="#cb47-5" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span> <span class="ot">=</span> <span class="st">&quot;#FF7F7F&quot;</span>, </span>
<span id="cb47-6"><a href="#cb47-6" tabindex="-1"></a>                                <span class="st">&quot;Fitted Values (Train)&quot;</span> <span class="ot">=</span> <span class="st">&quot;#6BC3FF&quot;</span>, </span>
<span id="cb47-7"><a href="#cb47-7" tabindex="-1"></a>                                <span class="st">&quot;Predicted Values (Test)&quot;</span> <span class="ot">=</span> <span class="st">&quot;#8FBC8F&quot;</span>),</span>
<span id="cb47-8"><a href="#cb47-8" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span>, <span class="st">&quot;Fitted Values (Train)&quot;</span>, <span class="st">&quot;Predicted Values (Test)&quot;</span>)) <span class="sc">+</span></span>
<span id="cb47-9"><a href="#cb47-9" tabindex="-1"></a>  </span>
<span id="cb47-10"><a href="#cb47-10" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb47-11"><a href="#cb47-11" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Actual vs Fitted and Predicted Values for Baccala Mantecato (Linear Regression Model)&quot;</span>,</span>
<span id="cb47-12"><a href="#cb47-12" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb47-13"><a href="#cb47-13" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Value&quot;</span>,</span>
<span id="cb47-14"><a href="#cb47-14" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;Legend&quot;</span></span>
<span id="cb47-15"><a href="#cb47-15" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb47-16"><a href="#cb47-16" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb47-17"><a href="#cb47-17" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/prediction_plot_baccala_mantecato-1.png" width="768" /></p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" tabindex="-1"></a>mse_test_lrm <span class="ot">&lt;-</span> <span class="fu">mse</span>(<span class="fu">predict</span>(lr_m, <span class="at">newdata =</span> test), test<span class="sc">$</span>Baccala_Mantecato)</span>
<span id="cb48-2"><a href="#cb48-2" tabindex="-1"></a><span class="fu">print</span>(mse_test_lrm)</span></code></pre></div>
<pre><code>## [1] 45.59531</code></pre>
</div>
<div id="baccala-vicentina" class="section level3">
<h3>Baccala Vicentina</h3>
<p>The same analysis is conducted below for the Baccala Vicentina
variable.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" tabindex="-1"></a>lr_v_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(Baccala_Vicentina <span class="sc">~</span> trend <span class="sc">+</span> Month <span class="sc">+</span> fish_cons, <span class="at">data =</span> train)</span>
<span id="cb50-2"><a href="#cb50-2" tabindex="-1"></a><span class="fu">summary</span>(lr_v_full)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Baccala_Vicentina ~ trend + Month + fish_cons, data = train)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.93656 -0.28770  0.03834  0.26048  1.04389 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  6.521439   0.385732  16.907 7.81e-15 ***
## trend       -0.003871   0.012914  -0.300 0.766943    
## Month02     -1.024427   0.533581  -1.920 0.066832 .  
## Month03     -0.545658   0.416915  -1.309 0.202997    
## Month04     -0.539178   0.414939  -1.299 0.206145    
## Month05      0.313648   0.413131   0.759 0.455128    
## Month06     -0.871432   0.434079  -2.008 0.056078 .  
## Month07      0.338424   0.469276   0.721 0.477776    
## Month08     -1.159240   0.426472  -2.718 0.011995 *  
## Month09      1.376043   0.441056   3.120 0.004660 ** 
## Month10     -1.650578   0.436545  -3.781 0.000915 ***
## Month11     -0.403319   0.465851  -0.866 0.395189    
## Month12      3.009990   0.421629   7.139 2.23e-07 ***
## fish_cons   -0.132469   0.216480  -0.612 0.546344    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5405 on 24 degrees of freedom
## Multiple R-squared:  0.8872, Adjusted R-squared:  0.8261 
## F-statistic: 14.52 on 13 and 24 DF,  p-value: 2.521e-08</code></pre>
<p>This time the fish consumption seems to be not useful to imporve the
model pefromance so we remove it</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" tabindex="-1"></a>lr_v <span class="ot">&lt;-</span> <span class="fu">update</span>(lr_v_full, .<span class="sc">~</span>. <span class="sc">-</span> fish_cons)</span>
<span id="cb52-2"><a href="#cb52-2" tabindex="-1"></a><span class="fu">summary</span>(lr_v)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Baccala_Vicentina ~ trend + Month, data = train)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.0267 -0.2963  0.0500  0.2662  1.0733 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  6.382778   0.308227  20.708  &lt; 2e-16 ***
## trend        0.002222   0.008120   0.274  0.78658    
## Month02     -1.252222   0.377455  -3.318  0.00278 ** 
## Month03     -0.516111   0.408896  -1.262  0.21852    
## Month04     -0.518333   0.408331  -1.269  0.21599    
## Month05      0.312778   0.407927   0.767  0.45041    
## Month06     -0.789444   0.407685  -1.936  0.06420 .  
## Month07      0.475000   0.407604   1.165  0.25488    
## Month08     -1.093889   0.407685  -2.683  0.01274 *  
## Month09      1.470556   0.407927   3.605  0.00136 ** 
## Month10     -1.565000   0.408331  -3.833  0.00076 ***
## Month11     -0.533889   0.408896  -1.306  0.20355    
## Month12      2.963889   0.409621   7.236 1.39e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5337 on 25 degrees of freedom
## Multiple R-squared:  0.8854, Adjusted R-squared:  0.8305 
## F-statistic:  16.1 on 12 and 25 DF,  p-value: 7.211e-09</code></pre>
<p>The adjusted R² increses from 0.8261 to 0.8305 suggesting that the
reduced model is better than the full one. Furthermore, the trend
variable shows a large p-value, suggesting that it can be removed from
the model without significantly affecting the results.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" tabindex="-1"></a>lr_v <span class="ot">&lt;-</span> <span class="fu">update</span>(lr_v, .<span class="sc">~</span>. <span class="sc">-</span> trend)</span>
<span id="cb54-2"><a href="#cb54-2" tabindex="-1"></a><span class="fu">summary</span>(lr_v)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Baccala_Vicentina ~ Month, data = train)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.0000 -0.3187  0.0500  0.2562  1.1000 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   6.4250     0.2620  24.518  &lt; 2e-16 ***
## Month02      -1.2500     0.3706  -3.373 0.002339 ** 
## Month03      -0.5250     0.4003  -1.312 0.201133    
## Month04      -0.5250     0.4003  -1.312 0.201133    
## Month05       0.3083     0.4003   0.770 0.448076    
## Month06      -0.7917     0.4003  -1.978 0.058647 .  
## Month07       0.4750     0.4003   1.187 0.246096    
## Month08      -1.0917     0.4003  -2.727 0.011289 *  
## Month09       1.4750     0.4003   3.685 0.001058 ** 
## Month10      -1.5583     0.4003  -3.893 0.000618 ***
## Month11      -0.5250     0.4003  -1.312 0.201133    
## Month12       2.9750     0.4003   7.432 6.84e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5241 on 26 degrees of freedom
## Multiple R-squared:  0.8851, Adjusted R-squared:  0.8365 
## F-statistic: 18.21 on 11 and 26 DF,  p-value: 1.684e-09</code></pre>
<p>The best model for the Baccala Vicentina series is the one that
includes only the monthly seasonality. This model provides the best fit,
indicating that the variations in the data are primarily driven by
seasonal effects, without the need for additional trend or other
predictors. Moreover, the fitted model is statistically significant, as
shown by the F-statistic of 18.21, with a p-value of 1.684e-09,
confirming the model’s overall significance.</p>
<p>Below, we compare the difference in AIC and adjusted R² between the
full model and the one with only the monthly seasonality.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Model with month:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Model with month:</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  AIC:&quot;</span>, <span class="fu">AIC</span>(lr_v), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>##   AIC: 70.31701</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  Adjusted R²:&quot;</span>, <span class="fu">summary</span>(lr_v)<span class="sc">$</span>adj.r.squared, <span class="st">&quot;</span><span class="sc">\n\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>##   Adjusted R²: 0.8364892</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Full model:</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Full model:</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  AIC:&quot;</span>, <span class="fu">AIC</span>(lr_v_full), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>##   AIC: 73.61503</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;  Adjusted R²:&quot;</span>, <span class="fu">summary</span>(lr_v_full)<span class="sc">$</span>adj.r.squared, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>##   Adjusted R²: 0.8261056</code></pre>
<p>The model with only the monthly seasonality performs better than the
full model in terms of both AIC and adjusted R².</p>
<p>Finally we will analyze the residuals.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" tabindex="-1"></a>resid_lrv <span class="ot">&lt;-</span> <span class="fu">residuals</span>(lr_v)</span>
<span id="cb68-2"><a href="#cb68-2" tabindex="-1"></a>mse_train_lrv <span class="ot">&lt;-</span> <span class="fu">mean</span>(resid_lrv<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb68-3"><a href="#cb68-3" tabindex="-1"></a><span class="co">#checkresiduals(lr_v)</span></span>
<span id="cb68-4"><a href="#cb68-4" tabindex="-1"></a><span class="fu">tsdisplay</span>(resid_lrv)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/residual_analysis_baccala_vicentina-1.png" width="768" /></p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" tabindex="-1"></a><span class="fu">dwtest</span>(lr_v)</span></code></pre></div>
<pre><code>## 
##  Durbin-Watson test
## 
## data:  lr_v
## DW = 1.5926, p-value = 0.18
## alternative hypothesis: true autocorrelation is greater than 0</code></pre>
<p>The Durbin-Watson test, that is used to check for autocorrelation in
the residuals of a regression model.mSince the p-value is greater than
the significance level (0.05), we reject the null hypothesis.</p>
<p>Finally we plot the predicted values and the actual ones. We also
compute the MSE on the test set.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb71-2"><a href="#cb71-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> data<span class="sc">$</span>Date, <span class="at">y =</span> data<span class="sc">$</span>Baccala_Vicentina, <span class="at">color =</span> <span class="st">&quot;Actual Values&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb71-3"><a href="#cb71-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> train<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">fitted</span>(lr_v), <span class="at">color =</span> <span class="st">&quot;Fitted Values (Train)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb71-4"><a href="#cb71-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> test<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">predict</span>(lr_v, <span class="at">newdata =</span> test), <span class="at">color =</span> <span class="st">&quot;Predicted Values (Test)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb71-5"><a href="#cb71-5" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span> <span class="ot">=</span> <span class="st">&quot;#FF7F7F&quot;</span>, </span>
<span id="cb71-6"><a href="#cb71-6" tabindex="-1"></a>                                <span class="st">&quot;Fitted Values (Train)&quot;</span> <span class="ot">=</span> <span class="st">&quot;#6BC3FF&quot;</span>, </span>
<span id="cb71-7"><a href="#cb71-7" tabindex="-1"></a>                                <span class="st">&quot;Predicted Values (Test)&quot;</span> <span class="ot">=</span> <span class="st">&quot;#8FBC8F&quot;</span>),</span>
<span id="cb71-8"><a href="#cb71-8" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span>, <span class="st">&quot;Fitted Values (Train)&quot;</span>, <span class="st">&quot;Predicted Values (Test)&quot;</span>)) <span class="sc">+</span></span>
<span id="cb71-9"><a href="#cb71-9" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb71-10"><a href="#cb71-10" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Actual vs Fitted and Predicted Values for Baccala Vicentina (Linear Regression Model)&quot;</span>,</span>
<span id="cb71-11"><a href="#cb71-11" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb71-12"><a href="#cb71-12" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Value&quot;</span>,</span>
<span id="cb71-13"><a href="#cb71-13" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;Legend&quot;</span></span>
<span id="cb71-14"><a href="#cb71-14" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb71-15"><a href="#cb71-15" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb71-16"><a href="#cb71-16" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/prediction_plot_baccala_vicentina-1.png" width="768" /></p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" tabindex="-1"></a>mse_test_lrv <span class="ot">&lt;-</span> <span class="fu">mse</span>(<span class="fu">predict</span>(lr_v, <span class="at">newdata =</span> test), test<span class="sc">$</span>Baccala_Vicentina)</span>
<span id="cb72-2"><a href="#cb72-2" tabindex="-1"></a><span class="fu">print</span>(mse_test_lrv)</span></code></pre></div>
<pre><code>## [1] 1.512444</code></pre>
</div>
</div>
<div id="gam-models" class="section level2">
<h2>GAM Models</h2>
<div id="baccala-mantecato-1" class="section level3">
<h3>Baccala Mantecato</h3>
<p>Now we explore if we can benefit from non-linear models, in
particular we try a GAM model and compare it with the Multiple Linear
Regression selected model. We start from the LR model</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" tabindex="-1"></a>g0 <span class="ot">=</span> <span class="fu">gam</span>(Baccala_Mantecato <span class="sc">~</span> trend <span class="sc">+</span> Month <span class="sc">+</span> fish_cons, <span class="at">data =</span> train) <span class="co">#this is equivalent to lr_m</span></span></code></pre></div>
<p>Now we plot the linear effects to see if they may require smoothing
functions</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb75-2"><a href="#cb75-2" tabindex="-1"></a><span class="fu">plot</span>(g0)</span></code></pre></div>
<pre><code>## Warning in gplot.default(x = c(&quot;01&quot;, &quot;02&quot;, &quot;03&quot;, &quot;04&quot;, &quot;05&quot;, &quot;06&quot;, &quot;07&quot;, : The
## &quot;x&quot; component of &quot;partial for Month&quot; has class &quot;character&quot;; no gplot() methods
## available</code></pre>
<p><img src="FINAL_CODE_NEW_files/figure-html/gam_analysis_baccala_mantecato_2-1.png" width="768" /></p>
<p>We clearly see a perfectly linear relation between the predictors and
the response variable, this plots suggests to stop our non-linear
analysis. To be sure we try anyway to include smoothing variables</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" tabindex="-1"></a>g1 <span class="ot">&lt;-</span> <span class="fu">gam</span>(Baccala_Mantecato <span class="sc">~</span> <span class="fu">s</span>(trend, <span class="at">df=</span><span class="dv">2</span>) <span class="sc">+</span> Month <span class="sc">+</span> <span class="fu">s</span>(fish_cons, <span class="at">df=</span><span class="dv">2</span>), <span class="at">data =</span> train)</span>
<span id="cb77-2"><a href="#cb77-2" tabindex="-1"></a><span class="fu">summary</span>(g1)</span></code></pre></div>
<pre><code>## 
## Call: gam(formula = Baccala_Mantecato ~ s(trend, df = 2) + Month + 
##     s(fish_cons, df = 2), data = train)
## Deviance Residuals:
##      Min       1Q   Median       3Q      Max 
## -4.15544 -1.31407 -0.09549  1.61239  5.67812 
## 
## (Dispersion Parameter for gaussian family taken to be 9.2934)
## 
##     Null Deviance: 3131.195 on 37 degrees of freedom
## Residual Deviance: 204.4537 on 21.9999 degrees of freedom
## AIC: 205.7842 
## 
## Number of Local Scoring Iterations: NA 
## 
## Anova for Parametric Effects
##                      Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## s(trend, df = 2)      1   57.33  57.329  6.1687    0.0211 *  
## Month                11 2353.98 213.998 23.0269 1.498e-09 ***
## s(fish_cons, df = 2)  1  314.04 314.042 33.7919 7.550e-06 ***
## Residuals            22  204.45   9.293                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Anova for Nonparametric Effects
##                      Npar Df Npar F   Pr(F)  
## (Intercept)                                  
## s(trend, df = 2)           1 1.7976 0.19369  
## Month                                        
## s(fish_cons, df = 2)       1 3.3753 0.07973 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Based on the df and on the ‘Anova for Nonparametric Effects’ results,
where the nonparametric F-values for s(trend) and s(fish_cons) are not
statistically significant (with p-values of 0.19369 and 0.07973
respectively), it is clear that these variables do not exhibit nonlinear
relationships with the response variable as we initially expected.
Therefore, for reasons of parsimony, interpretability, and simplicity,
we exclude the GAM model in favor of a straightforward multiple linear
regression model, which aligns better with the data and offers more
meaningful results.</p>
</div>
<div id="baccala-vicentina-1" class="section level3">
<h3>Baccala Vicentina</h3>
<p>Let’s see if the same holds for Baccala_Vicentina.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" tabindex="-1"></a>g0_v <span class="ot">=</span> <span class="fu">gam</span>(Baccala_Vicentina <span class="sc">~</span> trend <span class="sc">+</span> Month <span class="sc">+</span> fish_cons, <span class="at">data =</span> train) <span class="co">#this is equivalent to lr_v_full (remember that the best one was lr_v (only Month as X))</span></span>
<span id="cb79-2"><a href="#cb79-2" tabindex="-1"></a></span>
<span id="cb79-3"><a href="#cb79-3" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb79-4"><a href="#cb79-4" tabindex="-1"></a><span class="fu">plot</span>(g0)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/gam_analysis_baccala_vicentina-1.png" width="768" /></p>
<p>we clearly see that the behaviour of the explenatory variables is
still linear. This suggests to keep the linear regression model, but we
have also seen, in the section dedicated to linear regression, that for
Baccala_Vicentina the best model was the reduced one obtained by
considering only the Month variable as predictor. So we keep it.</p>
<p>This analysis clearly indicates that both results suggest against the
use of models that fit nonlinear relationships, such as GAMs.</p>
</div>
</div>
<div id="sarima-model" class="section level2">
<h2>SARIMA Model</h2>
<div id="baccala-mantecato-2" class="section level3">
<h3>Baccala Mantecato</h3>
<p>To begin, we first transform the sales data of Baccala Mantecato into
a time series object:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" tabindex="-1"></a>ts_m <span class="ot">&lt;-</span> <span class="fu">ts</span>(train<span class="sc">$</span>Baccala_Mantecato, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">2021</span>, <span class="dv">01</span>), <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb80-2"><a href="#cb80-2" tabindex="-1"></a><span class="fu">plot.ts</span>(ts_m)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/ts_m-1.png" width="768" />
From the plot above and the significance of the trend coefficient in the
regression model discussed in the previous section, we might consider
taking the first difference to observe the behavior of the ACF and
PACF.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" tabindex="-1"></a>ts_m1 <span class="ot">&lt;-</span> <span class="fu">diff</span>(ts_m,<span class="dv">1</span>)</span>
<span id="cb81-2"><a href="#cb81-2" tabindex="-1"></a><span class="fu">tsdisplay</span>(<span class="fu">diff</span>(ts_m,<span class="dv">1</span>))</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/ts_M_1-1.png" width="768" /></p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" tabindex="-1"></a><span class="co">#Acf(ts_m1, main = &quot;ACF of Baccala Mantecato with Lag 1&quot;, col = &quot;#FF7F7F&quot;, lwd = 2)</span></span>
<span id="cb82-2"><a href="#cb82-2" tabindex="-1"></a><span class="co">#Pacf(ts_m1, main = &quot;PACF of Baccala Mantecato with Lag 1&quot;, col = &quot;#6BC3FF&quot;, lwd = 2)</span></span></code></pre></div>
<p>Both the ACF and PACF plots show a sinusoidal pattern, with all
values falling within the confidence bands, except for a significant
spike at lag 12. This suggests that a SARIMA model with a seasonal
period s=12, accounting for monthly data with yearly seasonality, might
be appropriate for this time series.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" tabindex="-1"></a>ts_m_12 <span class="ot">&lt;-</span> <span class="fu">diff</span>(ts_m, <span class="at">lag =</span> <span class="dv">12</span>)</span>
<span id="cb83-2"><a href="#cb83-2" tabindex="-1"></a><span class="fu">tsdisplay</span>(<span class="fu">diff</span>(ts_m, <span class="at">lag =</span> <span class="dv">12</span>))</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/ts_M_12-1.png" width="768" /></p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" tabindex="-1"></a><span class="co">#Acf(ts_m_12, main = &quot;ACF of Baccala Mantecato with Lag 12&quot;, col = &quot;#FF7F7F&quot;, lwd = 2)</span></span>
<span id="cb84-2"><a href="#cb84-2" tabindex="-1"></a><span class="co">#Pacf(ts_m_12, main = &quot;PACF of Baccala Mantecato with Lag 12&quot;, col = &quot;#6BC3FF&quot;, lwd = 2)</span></span></code></pre></div>
<p>Now, we will build three SARIMA models. The first model will
incorporate a non-seasonal differencing (with d=1), one autoregressive
term (AR(1)), and a seasonal differencing with a period of 12 (to
account for the yearly seasonality). The second model will instead
include a moving average (MA(1)) term along with the differencing. The
last one only incorporate the differencing.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" tabindex="-1"></a><span class="co"># SARIMA (1,1,0)(0,1,0)[12]</span></span>
<span id="cb85-2"><a href="#cb85-2" tabindex="-1"></a>sarima_model1m <span class="ot">&lt;-</span> <span class="fu">Arima</span>(ts_m, <span class="at">order=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">seasonal=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>))</span>
<span id="cb85-3"><a href="#cb85-3" tabindex="-1"></a><span class="fu">summary</span>(sarima_model1m)</span></code></pre></div>
<pre><code>## Series: ts_m 
## ARIMA(1,1,0)(0,1,0)[12] 
## 
## Coefficients:
##           ar1
##       -0.4026
## s.e.   0.1950
## 
## sigma^2 = 40.08:  log likelihood = -81.19
## AIC=166.38   AICc=166.92   BIC=168.81
## 
## Training set error measures:
##                     ME     RMSE      MAE      MPE     MAPE      MASE
## Training set 0.4121828 5.031449 3.569755 0.974692 13.28395 0.5866855
##                     ACF1
## Training set -0.04953755</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" tabindex="-1"></a><span class="co"># SARIMA (0,1,1)(0,1,0)[12]</span></span>
<span id="cb87-2"><a href="#cb87-2" tabindex="-1"></a>sarima_model2m <span class="ot">&lt;-</span> <span class="fu">Arima</span>(ts_m, <span class="at">order=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">seasonal=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>))</span>
<span id="cb87-3"><a href="#cb87-3" tabindex="-1"></a><span class="fu">summary</span>(sarima_model2m)</span></code></pre></div>
<pre><code>## Series: ts_m 
## ARIMA(0,1,1)(0,1,0)[12] 
## 
## Coefficients:
##           ma1
##       -0.5335
## s.e.   0.1759
## 
## sigma^2 = 37.53:  log likelihood = -80.44
## AIC=164.89   AICc=165.43   BIC=167.33
## 
## Training set error measures:
##                     ME     RMSE      MAE      MPE   MAPE      MASE       ACF1
## Training set 0.5566444 4.868457 3.307765 1.377379 11.934 0.5436276 0.01044316</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" tabindex="-1"></a><span class="co"># SARIMA (0,1,0)(0,1,0)[12]</span></span>
<span id="cb89-2"><a href="#cb89-2" tabindex="-1"></a>sarima_model3m <span class="ot">&lt;-</span> <span class="fu">Arima</span>(ts_m, <span class="at">order=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>), <span class="at">seasonal=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>))</span>
<span id="cb89-3"><a href="#cb89-3" tabindex="-1"></a><span class="fu">summary</span>(sarima_model3m)</span></code></pre></div>
<pre><code>## Series: ts_m 
## ARIMA(0,1,0)(0,1,0)[12] 
## 
## sigma^2 = 45.23:  log likelihood = -83.12
## AIC=168.24   AICc=168.42   BIC=169.46
## 
## Training set error measures:
##                     ME     RMSE      MAE       MPE     MAPE      MASE
## Training set 0.2132482 5.455083 3.737677 0.7053902 13.76125 0.6142832
##                    ACF1
## Training set -0.3595701</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" tabindex="-1"></a><span class="fu">mse</span>(test<span class="sc">$</span>Baccala_Mantecato, <span class="fu">forecast</span>(sarima_model1m, <span class="at">h =</span> <span class="fu">length</span>(y_testm))<span class="sc">$</span>mean)</span></code></pre></div>
<pre><code>## [1] 126.6163</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" tabindex="-1"></a><span class="fu">mse</span>(test<span class="sc">$</span>Baccala_Mantecato, <span class="fu">forecast</span>(sarima_model2m, <span class="at">h =</span> <span class="fu">length</span>(y_testm))<span class="sc">$</span>mean)</span></code></pre></div>
<pre><code>## [1] 117.978</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" tabindex="-1"></a>mse_test_sarimam <span class="ot">&lt;-</span> <span class="fu">mse</span>(test<span class="sc">$</span>Baccala_Mantecato, <span class="fu">forecast</span>(sarima_model3m, <span class="at">h =</span> <span class="fu">length</span>(y_testm))<span class="sc">$</span>mean)</span>
<span id="cb95-2"><a href="#cb95-2" tabindex="-1"></a>mse_test_sarimam</span></code></pre></div>
<pre><code>## [1] 104.505</code></pre>
<p>Based on the AIC values, the SARIMA(0,1,1)(0,1,0)[12] model is the
better model. It has a lower AIC compared to the other SARIMA models. By
the way, evaluating the performance on the test set, we notice that the
MSE is larger for the AIC best model, while the SARIMA(0,1,0)(0,1,0)[12]
perform better on the test set. We decide to continue whit the last
one.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb97-2"><a href="#cb97-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> data<span class="sc">$</span>Date, <span class="at">y =</span> data<span class="sc">$</span>Baccala_Mantecato, <span class="at">color =</span> <span class="st">&quot;Actual Values&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb97-3"><a href="#cb97-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> train<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">fitted</span>(sarima_model3m), <span class="at">color =</span> <span class="st">&quot;Fitted Values (Train)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb97-4"><a href="#cb97-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> test<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">forecast</span>(sarima_model3m, <span class="at">h =</span> <span class="fu">nrow</span>(test))<span class="sc">$</span>mean, </span>
<span id="cb97-5"><a href="#cb97-5" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Predicted Values (Test)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb97-6"><a href="#cb97-6" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span> <span class="ot">=</span> <span class="st">&quot;#FF7F7F&quot;</span>, </span>
<span id="cb97-7"><a href="#cb97-7" tabindex="-1"></a>                                <span class="st">&quot;Fitted Values (Train)&quot;</span> <span class="ot">=</span> <span class="st">&quot;#6BC3FF&quot;</span>, </span>
<span id="cb97-8"><a href="#cb97-8" tabindex="-1"></a>                                <span class="st">&quot;Predicted Values (Test)&quot;</span> <span class="ot">=</span> <span class="st">&quot;#8FBC8F&quot;</span>),</span>
<span id="cb97-9"><a href="#cb97-9" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span>, <span class="st">&quot;Fitted Values (Train)&quot;</span>, <span class="st">&quot;Predicted Values (Test)&quot;</span>)) <span class="sc">+</span></span>
<span id="cb97-10"><a href="#cb97-10" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb97-11"><a href="#cb97-11" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Actual vs Fitted and Predicted Values for Baccala Vicentina (SARIMA Model)&quot;</span>,</span>
<span id="cb97-12"><a href="#cb97-12" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb97-13"><a href="#cb97-13" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Value&quot;</span>,</span>
<span id="cb97-14"><a href="#cb97-14" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;Legend&quot;</span></span>
<span id="cb97-15"><a href="#cb97-15" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb97-16"><a href="#cb97-16" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb97-17"><a href="#cb97-17" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/prediction_plot_baccala_mantecato_sarima-1.png" width="768" /></p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" tabindex="-1"></a>resid3 <span class="ot">&lt;-</span> <span class="fu">residuals</span>(sarima_model3m)</span>
<span id="cb98-2"><a href="#cb98-2" tabindex="-1"></a>mse_train_sarimam <span class="ot">&lt;-</span> <span class="fu">mean</span>(resid3<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb98-3"><a href="#cb98-3" tabindex="-1"></a><span class="fu">tsdisplay</span>(resid3)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/residual_analysis_baccala_mantecato__-1.png" width="768" /></p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" tabindex="-1"></a><span class="co">#Acf(resid3, main = &quot;ACF for SARIMA Residuals of Baccala Mantecato&quot;, col = &quot;#FF7F7F&quot;, lwd = 2)</span></span>
<span id="cb99-2"><a href="#cb99-2" tabindex="-1"></a><span class="co">#Pacf(resid3, main = &quot;PACF for SARIMA Residuals of Baccala Mantecato&quot;, col = &quot;#6BC3FF&quot;, lwd = 2)</span></span></code></pre></div>
<p>Residuals does not suggest a really good fit but, as said before, the
best test performance are reached by the selected model.</p>
</div>
<div id="baccala-vicentina-2" class="section level3">
<h3>Baccala Vicentina</h3>
<p>To begin, we first transform the sales data of Baccalá Vicentina into
a time series object:</p>
<div class="sourceCode" id="cb100"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" tabindex="-1"></a>ts_v <span class="ot">&lt;-</span> <span class="fu">ts</span>(train<span class="sc">$</span>Baccala_Vicentina, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">2021</span>, <span class="dv">01</span>), <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb100-2"><a href="#cb100-2" tabindex="-1"></a><span class="fu">plot.ts</span>(ts_v)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/ts_V-1.png" width="768" /></p>
<div class="sourceCode" id="cb101"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" tabindex="-1"></a><span class="fu">tsdisplay</span>(ts_v)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/acf_pacf_analysis_baccala_vicentina_-1.png" width="768" /></p>
<div class="sourceCode" id="cb102"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" tabindex="-1"></a><span class="fu">Acf</span>(ts_v, <span class="at">main =</span> <span class="st">&quot;ACF of Baccala Vicentina&quot;</span>, <span class="at">col =</span> <span class="st">&quot;#FF7F7F&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/acf_pacf_analysis_baccala_vicentina_-2.png" width="768" /></p>
<div class="sourceCode" id="cb103"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" tabindex="-1"></a><span class="fu">Pacf</span>(ts_v, <span class="at">main =</span> <span class="st">&quot;PACF of Baccala Vicentina&quot;</span>, <span class="at">col =</span> <span class="st">&quot;#6BC3FF&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/acf_pacf_analysis_baccala_vicentina_-3.png" width="768" /></p>
<p>From the plot above we clearly notice the presence of seasonality
that is confirmed by the pacf and acf functions with a significant spike
at lag 12.</p>
<div class="sourceCode" id="cb104"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" tabindex="-1"></a>ts_v_12 <span class="ot">&lt;-</span> <span class="fu">diff</span>(ts_v, <span class="at">lag =</span> <span class="dv">12</span>)</span>
<span id="cb104-2"><a href="#cb104-2" tabindex="-1"></a><span class="fu">tsdisplay</span>(ts_v_12)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/acf_pacf_analysis_baccala_vicentina-1.png" width="768" /></p>
<div class="sourceCode" id="cb105"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" tabindex="-1"></a><span class="fu">Acf</span>(ts_v_12, <span class="at">main =</span> <span class="st">&quot;ACF of Baccala Vicentina with Lag 12&quot;</span>, <span class="at">col =</span> <span class="st">&quot;#FF7F7F&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/acf_pacf_analysis_baccala_vicentina-2.png" width="768" /></p>
<div class="sourceCode" id="cb106"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" tabindex="-1"></a><span class="fu">Pacf</span>(ts_v_12, <span class="at">main =</span> <span class="st">&quot;PACF of Baccala Vicentina with Lag 12&quot;</span>, <span class="at">col =</span> <span class="st">&quot;#6BC3FF&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/acf_pacf_analysis_baccala_vicentina-3.png" width="768" /></p>
<p>This suggests that a SARIMA model with a seasonal period s=12,
accounting for monthly data with yearly seasonality, might be
appropriate for this time series.</p>
<p>Now, we will build a SARIMA model model that incorporate only a
seasonal differencing with a period of 12. The parameter D=2 lead us to
lower AIC but a bigger mse, this is a case of overfitting.</p>
<div class="sourceCode" id="cb107"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" tabindex="-1"></a>auto_sarima_modelv <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(ts_v)</span>
<span id="cb107-2"><a href="#cb107-2" tabindex="-1"></a><span class="fu">summary</span>(auto_sarima_modelv)</span></code></pre></div>
<pre><code>## Series: ts_v 
## ARIMA(0,0,0)(0,1,0)[12] 
## 
## sigma^2 = 0.5269:  log likelihood = -28.56
## AIC=59.13   AICc=59.29   BIC=60.38
## 
## Training set error measures:
##                      ME      RMSE       MAE        MPE     MAPE      MASE
## Training set 0.01779737 0.6004495 0.4072711 -0.1956312 6.652206 0.6876005
##                   ACF1
## Training set 0.1744926</code></pre>
<div class="sourceCode" id="cb109"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" tabindex="-1"></a><span class="co"># SARIMA(0,0,0)(0,1,0)[12]</span></span>
<span id="cb109-2"><a href="#cb109-2" tabindex="-1"></a>sarima_model2v <span class="ot">&lt;-</span> <span class="fu">Arima</span>(ts_v, <span class="at">order=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">seasonal=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>))</span>
<span id="cb109-3"><a href="#cb109-3" tabindex="-1"></a><span class="fu">summary</span>(sarima_model2v)</span></code></pre></div>
<pre><code>## Series: ts_v 
## ARIMA(0,0,0)(0,1,0)[12] 
## 
## sigma^2 = 0.5269:  log likelihood = -28.56
## AIC=59.13   AICc=59.29   BIC=60.38
## 
## Training set error measures:
##                      ME      RMSE       MAE        MPE     MAPE      MASE
## Training set 0.01779737 0.6004495 0.4072711 -0.1956312 6.652206 0.6876005
##                   ACF1
## Training set 0.1744926</code></pre>
<div class="sourceCode" id="cb111"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" tabindex="-1"></a>resid2 <span class="ot">&lt;-</span> <span class="fu">residuals</span>(sarima_model2v)</span>
<span id="cb111-2"><a href="#cb111-2" tabindex="-1"></a>mse_train_sarimav <span class="ot">&lt;-</span> <span class="fu">mean</span>(resid2<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb111-3"><a href="#cb111-3" tabindex="-1"></a><span class="fu">tsdisplay</span>(resid2)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/mse_sarima_baccala_vicentina-1.png" width="768" /></p>
<div class="sourceCode" id="cb112"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" tabindex="-1"></a><span class="co">#Acf(resid2, main = &quot;ACF for SARIMA Residuals of Baccala Vicentina&quot;, col = &quot;#FF7F7F&quot;, lwd = 2)</span></span>
<span id="cb112-2"><a href="#cb112-2" tabindex="-1"></a><span class="co">#Pacf(resid2, main = &quot;PACF for SARIMA Residuals of Baccala Vicentina&quot;, col = &quot;#6BC3FF&quot;, lwd = 2)</span></span></code></pre></div>
<p>The best model based on AIC is supposed to be the
SARIMA(0,0,0)(0,1,0)[12].</p>
<div class="sourceCode" id="cb113"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" tabindex="-1"></a>mse_test_sarimav <span class="ot">&lt;-</span> <span class="fu">mse</span>(test<span class="sc">$</span>Baccala_Vicentina, <span class="fu">forecast</span>(sarima_model2v, <span class="at">h =</span> <span class="fu">length</span>(y_testv))<span class="sc">$</span>mean)</span>
<span id="cb113-2"><a href="#cb113-2" tabindex="-1"></a>mse_test_sarimav</span></code></pre></div>
<pre><code>## [1] 2.265</code></pre>
<p>Note: We also tried different configurations, expecially after we saw
the residuals plot, where most of the values are inside the bandswith
butfrom the ts plot their behaviou don’t seems to be a random noise one;
but at the end, this remain the best model. possible.</p>
<div class="sourceCode" id="cb115"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb115-2"><a href="#cb115-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> data<span class="sc">$</span>Date, <span class="at">y =</span> data<span class="sc">$</span>Baccala_Vicentina, <span class="at">color =</span> <span class="st">&quot;Actual Values&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb115-3"><a href="#cb115-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> train<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">fitted</span>(sarima_model2v), <span class="at">color =</span> <span class="st">&quot;Fitted Values (Train)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb115-4"><a href="#cb115-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> test<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">forecast</span>(sarima_model2v, <span class="at">h =</span> <span class="fu">nrow</span>(test))<span class="sc">$</span>mean, </span>
<span id="cb115-5"><a href="#cb115-5" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Predicted Values (Test)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb115-6"><a href="#cb115-6" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span> <span class="ot">=</span> <span class="st">&quot;#FF7F7F&quot;</span>, </span>
<span id="cb115-7"><a href="#cb115-7" tabindex="-1"></a>                                <span class="st">&quot;Fitted Values (Train)&quot;</span> <span class="ot">=</span> <span class="st">&quot;#6BC3FF&quot;</span>, </span>
<span id="cb115-8"><a href="#cb115-8" tabindex="-1"></a>                                <span class="st">&quot;Predicted Values (Test)&quot;</span> <span class="ot">=</span> <span class="st">&quot;#8FBC8F&quot;</span>),</span>
<span id="cb115-9"><a href="#cb115-9" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span>, <span class="st">&quot;Fitted Values (Train)&quot;</span>, <span class="st">&quot;Predicted Values (Test)&quot;</span>)) <span class="sc">+</span></span>
<span id="cb115-10"><a href="#cb115-10" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb115-11"><a href="#cb115-11" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Actual vs Fitted and Predicted Values for Baccala Vicentina (SARIMA Model)&quot;</span>,</span>
<span id="cb115-12"><a href="#cb115-12" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb115-13"><a href="#cb115-13" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Value&quot;</span>,</span>
<span id="cb115-14"><a href="#cb115-14" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;Legend&quot;</span></span>
<span id="cb115-15"><a href="#cb115-15" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb115-16"><a href="#cb115-16" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb115-17"><a href="#cb115-17" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/plot_sarima_baccala_vicentina-1.png" width="768" /></p>
</div>
</div>
<div id="armax" class="section level2">
<h2>ARMAX</h2>
<p>Now following the same reasoning of SARIMA models, we compare to them
the same models but also using the fish consumption information as xreg,
to see if it improves our results</p>
<div id="baccalà-mantecato" class="section level3">
<h3>Baccalà mantecato</h3>
<div class="sourceCode" id="cb116"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" tabindex="-1"></a>sarimax_model1m <span class="ot">&lt;-</span> <span class="fu">Arima</span>(ts_m, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">xreg =</span> train<span class="sc">$</span>fish_cons)</span>
<span id="cb116-2"><a href="#cb116-2" tabindex="-1"></a>sarimax_model2m <span class="ot">&lt;-</span> <span class="fu">Arima</span>(ts_m, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">xreg =</span> train<span class="sc">$</span>fish_cons)</span>
<span id="cb116-3"><a href="#cb116-3" tabindex="-1"></a>sarimax_model3m <span class="ot">&lt;-</span> <span class="fu">Arima</span>(ts_m, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">xreg =</span> train<span class="sc">$</span>fish_cons)</span></code></pre></div>
<p>Once we have fitted the models, we compare them to the previous
SARIMA considering the AIC as metric</p>
<div class="sourceCode" id="cb117"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" tabindex="-1"></a><span class="fu">AIC</span>(sarima_model1m, sarimax_model1m)</span></code></pre></div>
<pre><code>##                 df      AIC
## sarima_model1m   2 166.3764
## sarimax_model1m  3 143.8121</code></pre>
<div class="sourceCode" id="cb119"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" tabindex="-1"></a><span class="fu">AIC</span>(sarima_model2m, sarimax_model2m)</span></code></pre></div>
<pre><code>##                 df      AIC
## sarima_model2m   2 164.8879
## sarimax_model2m  3 144.8067</code></pre>
<div class="sourceCode" id="cb121"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" tabindex="-1"></a><span class="fu">AIC</span>(sarima_model3m, sarimax_model3m)</span></code></pre></div>
<pre><code>##                 df      AIC
## sarima_model3m   1 168.2416
## sarimax_model3m  2 151.9159</code></pre>
<p>It is clear that using the fish consumption data we improve the
models, but as we’ve seen for SARIMAs, considering only AIC may not be
enough, so now we also look at the MSEs</p>
<div class="sourceCode" id="cb123"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" tabindex="-1"></a><span class="fu">mse</span>(test<span class="sc">$</span>Baccala_Mantecato, <span class="fu">forecast</span>(sarima_model1m, <span class="at">h =</span> <span class="fu">length</span>(y_testm))<span class="sc">$</span>mean)</span></code></pre></div>
<pre><code>## [1] 126.6163</code></pre>
<div class="sourceCode" id="cb125"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" tabindex="-1"></a><span class="fu">mse</span>(test<span class="sc">$</span>Baccala_Mantecato, <span class="fu">forecast</span>(sarimax_model1m, <span class="at">h =</span> <span class="fu">length</span>(y_testm),<span class="at">xreg =</span> test<span class="sc">$</span>fish_cons)<span class="sc">$</span>mean)</span></code></pre></div>
<pre><code>## [1] 64.51161</code></pre>
<div class="sourceCode" id="cb127"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" tabindex="-1"></a><span class="fu">mse</span>(test<span class="sc">$</span>Baccala_Mantecato, <span class="fu">forecast</span>(sarima_model2m, <span class="at">h =</span> <span class="fu">length</span>(y_testm))<span class="sc">$</span>mean)</span></code></pre></div>
<pre><code>## [1] 117.978</code></pre>
<div class="sourceCode" id="cb129"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" tabindex="-1"></a><span class="fu">mse</span>(test<span class="sc">$</span>Baccala_Mantecato, <span class="fu">forecast</span>(sarimax_model2m, <span class="at">h =</span> <span class="fu">length</span>(y_testm),<span class="at">xreg =</span> test<span class="sc">$</span>fish_cons)<span class="sc">$</span>mean)</span></code></pre></div>
<pre><code>## [1] 64.29656</code></pre>
<div class="sourceCode" id="cb131"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" tabindex="-1"></a><span class="fu">mse</span>(test<span class="sc">$</span>Baccala_Mantecato, <span class="fu">forecast</span>(sarima_model3m, <span class="at">h =</span> <span class="fu">length</span>(y_testm))<span class="sc">$</span>mean)</span></code></pre></div>
<pre><code>## [1] 104.505</code></pre>
<div class="sourceCode" id="cb133"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" tabindex="-1"></a>mse_test_sarimaxm <span class="ot">&lt;-</span> <span class="fu">mse</span>(test<span class="sc">$</span>Baccala_Mantecato, <span class="fu">forecast</span>(sarimax_model3m, <span class="at">h =</span> <span class="fu">length</span>(y_testm),<span class="at">xreg =</span> test<span class="sc">$</span>fish_cons)<span class="sc">$</span>mean)</span>
<span id="cb133-2"><a href="#cb133-2" tabindex="-1"></a>mse_test_sarimaxm</span></code></pre></div>
<pre><code>## [1] 64.05571</code></pre>
<p>We see that in terms of MSE, SARIMAX brings to huge improvements for
all 3 the considered models reducing the MSEs by approximately 50%.
Following the same reasoning as before, and considering both the AIC and
the MSE, among the models we select the ARMAX(0,1,0)(0,1,0)[12].</p>
<p>Now we look at that model prediction on the test set compared to the
respective original SARIMA</p>
<div class="sourceCode" id="cb135"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb135-2"><a href="#cb135-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> data<span class="sc">$</span>Date, <span class="at">y =</span> data<span class="sc">$</span>Baccala_Mantecato, <span class="at">color =</span> <span class="st">&quot;Actual Values&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb135-3"><a href="#cb135-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> test<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">forecast</span>(sarima_model3m, <span class="at">h =</span> <span class="fu">nrow</span>(test))<span class="sc">$</span>mean, </span>
<span id="cb135-4"><a href="#cb135-4" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Predicted Values (Test) SARIMA&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb135-5"><a href="#cb135-5" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> test<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">forecast</span>(sarimax_model3m, <span class="at">h =</span> <span class="fu">nrow</span>(test), <span class="at">xreg =</span> test<span class="sc">$</span>fish_cons)<span class="sc">$</span>mean, </span>
<span id="cb135-6"><a href="#cb135-6" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Predicted Values (Test) SARIMAX&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb135-7"><a href="#cb135-7" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span> <span class="ot">=</span> <span class="st">&quot;black&quot;</span>, </span>
<span id="cb135-8"><a href="#cb135-8" tabindex="-1"></a>                                <span class="st">&quot;Predicted Values (Test) SARIMA&quot;</span> <span class="ot">=</span> <span class="st">&quot;#6BC3FF&quot;</span>,</span>
<span id="cb135-9"><a href="#cb135-9" tabindex="-1"></a>                                <span class="st">&quot;Predicted Values (Test) SARIMAX&quot;</span> <span class="ot">=</span> <span class="st">&quot;#FF7F7F&quot;</span>),</span>
<span id="cb135-10"><a href="#cb135-10" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span>, <span class="st">&quot;Predicted Values (Test) SARIMA&quot;</span>, <span class="st">&quot;Predicted Values (Test) SARIMAX&quot;</span>)) <span class="sc">+</span></span>
<span id="cb135-11"><a href="#cb135-11" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb135-12"><a href="#cb135-12" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Actual vs Predicted Values for Baccala Mantecato (SARIMA vs SARIMAX)&quot;</span>,</span>
<span id="cb135-13"><a href="#cb135-13" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb135-14"><a href="#cb135-14" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Value&quot;</span>,</span>
<span id="cb135-15"><a href="#cb135-15" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;Legend&quot;</span></span>
<span id="cb135-16"><a href="#cb135-16" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb135-17"><a href="#cb135-17" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb135-18"><a href="#cb135-18" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/plot_sarimax_baccala_mantecato-1.png" width="768" /></p>
<p>From the plot we clearly see the improvement obtained with the
SARIMAX version, confirming that the fish_cons variable helps on
predicting future orders quantity.</p>
<p>Now we see the residuals</p>
<div class="sourceCode" id="cb136"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" tabindex="-1"></a>resid3_sarimax <span class="ot">&lt;-</span> <span class="fu">residuals</span>(sarimax_model3m)</span>
<span id="cb136-2"><a href="#cb136-2" tabindex="-1"></a>mse_train_sarimaxm <span class="ot">&lt;-</span> <span class="fu">mean</span>(resid3_sarimax<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb136-3"><a href="#cb136-3" tabindex="-1"></a><span class="fu">tsdisplay</span>(resid3_sarimax, <span class="at">main=</span><span class="st">&quot;SARIMAX(0,1,0)(0,1,0)[12] Residuals for Baccala Mantecato&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/residual_analysis_baccala_mantecato_-1.png" width="768" /></p>
<div class="sourceCode" id="cb137"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" tabindex="-1"></a><span class="co">#Acf(resid3_sarimax, main = &quot;ACF for SARIMAX Residuals of Baccala Mantecato&quot;, col = &quot;#FF7F7F&quot;, lwd = 2)</span></span>
<span id="cb137-2"><a href="#cb137-2" tabindex="-1"></a><span class="co">#Pacf(resid3_sarimax, main = &quot;PACF for SARIMAX Residuals of Baccala Mantecato&quot;, col = &quot;#6BC3FF&quot;, lwd = 2)</span></span></code></pre></div>
<p>From the acf we have the doubt that we are missing an autoregressive
component, but including it leads to lower performances on the test set,
so we decide to accept that loss of information showed in the residuals
to avoid overfitting.</p>
</div>
<div id="baccala-vicentina-3" class="section level3">
<h3>Baccala Vicentina</h3>
<p>Following the same approach, we try to study the effects of
considering fish_cons on Baccala_vicentina and compare it to the
previously selected SARIMA(0,1,1)(0,1,0)[12] model</p>
<div class="sourceCode" id="cb138"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" tabindex="-1"></a>sarimax_model2v <span class="ot">&lt;-</span> <span class="fu">Arima</span>(ts_v, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="at">seasonal =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">xreg =</span> train<span class="sc">$</span>fish_cons)</span>
<span id="cb138-2"><a href="#cb138-2" tabindex="-1"></a></span>
<span id="cb138-3"><a href="#cb138-3" tabindex="-1"></a><span class="fu">AIC</span>(sarima_model2v, sarimax_model2v)</span></code></pre></div>
<pre><code>## Warning in AIC.default(sarima_model2v, sarimax_model2v): models are not all
## fitted to the same number of observations</code></pre>
<pre><code>##                 df      AIC
## sarima_model2v   1 59.12659
## sarimax_model2v  3 64.19084</code></pre>
<div class="sourceCode" id="cb141"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" tabindex="-1"></a><span class="fu">mse</span>(test<span class="sc">$</span>Baccala_Vicentina, <span class="fu">forecast</span>(sarima_model2v, <span class="at">h =</span> <span class="fu">length</span>(y_testv))<span class="sc">$</span>mean)</span></code></pre></div>
<pre><code>## [1] 2.265</code></pre>
<div class="sourceCode" id="cb143"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" tabindex="-1"></a>mse_test_sarimaxv <span class="ot">&lt;-</span> <span class="fu">mse</span>(test<span class="sc">$</span>Baccala_Vicentina, <span class="fu">forecast</span>(sarimax_model2v, <span class="at">h =</span> <span class="fu">length</span>(y_testv), <span class="at">xreg =</span> test<span class="sc">$</span>fish_cons)<span class="sc">$</span>mean)</span>
<span id="cb143-2"><a href="#cb143-2" tabindex="-1"></a>mse_test_sarimaxv</span></code></pre></div>
<pre><code>## [1] 2.349442</code></pre>
<p>Surprisingly for the Baccala_Vicentina, the originally selected
SARIMA model performs better than the SARIMAX one considering both AIC
and MSE, so we discard it and select the original SARIMA.</p>
<div class="sourceCode" id="cb145"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb145-2"><a href="#cb145-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> data<span class="sc">$</span>Date, <span class="at">y =</span> data<span class="sc">$</span>Baccala_Vicentina, <span class="at">color =</span> <span class="st">&quot;Actual Values&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb145-3"><a href="#cb145-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> test<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">forecast</span>(sarima_model2v, <span class="at">h =</span> <span class="fu">nrow</span>(test))<span class="sc">$</span>mean, </span>
<span id="cb145-4"><a href="#cb145-4" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Predicted Values (Test) SARIMA&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb145-5"><a href="#cb145-5" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> test<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">forecast</span>(sarimax_model2v, <span class="at">h =</span> <span class="fu">nrow</span>(test), <span class="at">xreg =</span> test<span class="sc">$</span>fish_cons)<span class="sc">$</span>mean, </span>
<span id="cb145-6"><a href="#cb145-6" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Predicted Values (Test) SARIMAX&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb145-7"><a href="#cb145-7" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span> <span class="ot">=</span> <span class="st">&quot;black&quot;</span>, </span>
<span id="cb145-8"><a href="#cb145-8" tabindex="-1"></a>                                <span class="st">&quot;Predicted Values (Test) SARIMA&quot;</span> <span class="ot">=</span> <span class="st">&quot;#6BC3FF&quot;</span>,</span>
<span id="cb145-9"><a href="#cb145-9" tabindex="-1"></a>                                <span class="st">&quot;Predicted Values (Test) SARIMAX&quot;</span> <span class="ot">=</span> <span class="st">&quot;#FF7F7F&quot;</span>),</span>
<span id="cb145-10"><a href="#cb145-10" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span>, <span class="st">&quot;Predicted Values (Test) SARIMA&quot;</span>, <span class="st">&quot;Predicted Values (Test) SARIMAX&quot;</span>)) <span class="sc">+</span></span>
<span id="cb145-11"><a href="#cb145-11" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb145-12"><a href="#cb145-12" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Actual vs Predicted Values for Baccala Vicentina (SARIMA vs SARIMAX)&quot;</span>,</span>
<span id="cb145-13"><a href="#cb145-13" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb145-14"><a href="#cb145-14" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Value&quot;</span>,</span>
<span id="cb145-15"><a href="#cb145-15" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;Legend&quot;</span></span>
<span id="cb145-16"><a href="#cb145-16" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb145-17"><a href="#cb145-17" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb145-18"><a href="#cb145-18" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/plot_sarimax_baccala_vicentina-1.png" width="768" /></p>
<div class="sourceCode" id="cb146"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" tabindex="-1"></a>resid2_sarimax <span class="ot">&lt;-</span> <span class="fu">residuals</span>(sarimax_model2v)</span>
<span id="cb146-2"><a href="#cb146-2" tabindex="-1"></a>mse_train_sarimaxv <span class="ot">&lt;-</span> <span class="fu">mean</span>(resid2_sarimax<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<p>As we can see from the plot, the 2 predictions are very similar but
probably fish_cons and the peak that occurs every December except for
the last one, which coincidentally is the test set, lead the SARIMAX
model to overestimate the quantities sold, thus explaining the worse
results in terms of AIC and MSE obtained earlier. So we confirm that for
Baccala_Vicentina we discard the SARIMAX model.</p>
</div>
</div>
<div id="prophet-model" class="section level2">
<h2>Prophet Model</h2>
<div id="baccala-mantecato-3" class="section level3">
<h3>Baccala Mantecato</h3>
<p>We start by creating the dataset to give to the function
prophet()</p>
<div class="sourceCode" id="cb147"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" tabindex="-1"></a>proph_md <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb147-2"><a href="#cb147-2" tabindex="-1"></a>  <span class="at">ds =</span> train[,<span class="st">&quot;Date&quot;</span>],</span>
<span id="cb147-3"><a href="#cb147-3" tabindex="-1"></a>  <span class="at">y =</span> train[,<span class="st">&quot;Baccala_Mantecato&quot;</span>]</span>
<span id="cb147-4"><a href="#cb147-4" tabindex="-1"></a>)</span>
<span id="cb147-5"><a href="#cb147-5" tabindex="-1"></a><span class="fu">colnames</span>(proph_md) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;ds&quot;</span>, <span class="st">&quot;y&quot;</span>)</span>
<span id="cb147-6"><a href="#cb147-6" tabindex="-1"></a>proph_md<span class="sc">$</span>cap <span class="ot">&lt;-</span> <span class="fu">max</span>(proph_md<span class="sc">$</span>y) <span class="sc">*</span> <span class="fl">1.1</span></span>
<span id="cb147-7"><a href="#cb147-7" tabindex="-1"></a><span class="fu">str</span>(proph_md)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    38 obs. of  3 variables:
##  $ ds : Date, format: &quot;2021-01-01&quot; &quot;2021-02-01&quot; ...
##  $ y  : num  36.4 36.4 31.2 30.4 46.1 35.8 34.6 25.3 42.2 18.2 ...
##  $ cap: num  58.4 58.4 58.4 58.4 58.4 ...</code></pre>
<div class="sourceCode" id="cb149"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" tabindex="-1"></a>proph_logistic<span class="ot">=</span><span class="fu">prophet</span>(proph_md,  <span class="at">growth=</span><span class="st">&quot;logistic&quot;</span>, <span class="at">n.changepoints=</span><span class="dv">5</span>, </span>
<span id="cb149-2"><a href="#cb149-2" tabindex="-1"></a>           <span class="at">yearly.seasonality=</span><span class="cn">TRUE</span>, </span>
<span id="cb149-3"><a href="#cb149-3" tabindex="-1"></a>           <span class="at">seasonality.mode=</span><span class="st">&#39;multiplicative&#39;</span>)</span>
<span id="cb149-4"><a href="#cb149-4" tabindex="-1"></a></span>
<span id="cb149-5"><a href="#cb149-5" tabindex="-1"></a>proph_m<span class="ot">=</span><span class="fu">prophet</span>(proph_md,  <span class="at">growth=</span><span class="st">&quot;linear&quot;</span>, <span class="at">n.changepoints=</span><span class="dv">5</span>, </span>
<span id="cb149-6"><a href="#cb149-6" tabindex="-1"></a>           <span class="at">yearly.seasonality=</span><span class="cn">TRUE</span>, </span>
<span id="cb149-7"><a href="#cb149-7" tabindex="-1"></a>           <span class="at">seasonality.mode=</span><span class="st">&#39;multiplicative&#39;</span>)</span>
<span id="cb149-8"><a href="#cb149-8" tabindex="-1"></a></span>
<span id="cb149-9"><a href="#cb149-9" tabindex="-1"></a>future_logistic <span class="ot">&lt;-</span> <span class="fu">make_future_dataframe</span>(proph_logistic, <span class="at">periods =</span> <span class="dv">10</span>, <span class="at">freq =</span> <span class="st">&quot;month&quot;</span>, <span class="at">include_history =</span> T)</span>
<span id="cb149-10"><a href="#cb149-10" tabindex="-1"></a>future_logistic<span class="sc">$</span>cap <span class="ot">&lt;-</span> <span class="fu">max</span>(proph_md<span class="sc">$</span>y) <span class="sc">*</span> <span class="fl">1.1</span></span>
<span id="cb149-11"><a href="#cb149-11" tabindex="-1"></a>forecast_future_logistic <span class="ot">&lt;-</span> <span class="fu">predict</span>(proph_logistic, future_logistic)</span>
<span id="cb149-12"><a href="#cb149-12" tabindex="-1"></a>test_logistic <span class="ot">&lt;-</span> <span class="fu">tail</span>(forecast_future_logistic, <span class="dv">10</span>)</span>
<span id="cb149-13"><a href="#cb149-13" tabindex="-1"></a></span>
<span id="cb149-14"><a href="#cb149-14" tabindex="-1"></a><span class="fu">mean</span>((test<span class="sc">$</span>Baccala_Mantecato <span class="sc">-</span> test_logistic<span class="sc">$</span>yhat)<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 147.1989</code></pre>
<div class="sourceCode" id="cb151"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" tabindex="-1"></a>future <span class="ot">&lt;-</span> <span class="fu">make_future_dataframe</span>(proph_m, <span class="at">periods =</span> <span class="dv">10</span>, <span class="at">freq =</span> <span class="st">&quot;month&quot;</span>, <span class="at">include_history =</span> T)</span>
<span id="cb151-2"><a href="#cb151-2" tabindex="-1"></a>future<span class="sc">$</span>cap <span class="ot">&lt;-</span> <span class="fu">max</span>(proph_md<span class="sc">$</span>y) <span class="sc">*</span> <span class="fl">1.1</span></span>
<span id="cb151-3"><a href="#cb151-3" tabindex="-1"></a>forecast_future <span class="ot">&lt;-</span> <span class="fu">predict</span>(proph_m, future_logistic)</span>
<span id="cb151-4"><a href="#cb151-4" tabindex="-1"></a>test_m <span class="ot">&lt;-</span> <span class="fu">tail</span>(forecast_future, <span class="dv">10</span>)</span>
<span id="cb151-5"><a href="#cb151-5" tabindex="-1"></a></span>
<span id="cb151-6"><a href="#cb151-6" tabindex="-1"></a>mse_test_prm <span class="ot">&lt;-</span> <span class="fu">mean</span>((test<span class="sc">$</span>Baccala_Mantecato <span class="sc">-</span> test_m<span class="sc">$</span>yhat)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb151-7"><a href="#cb151-7" tabindex="-1"></a>mse_test_prm</span></code></pre></div>
<pre><code>## [1] 119.073</code></pre>
<p>Visualize the rpedictions below.</p>
<div class="sourceCode" id="cb153"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" tabindex="-1"></a>forecast_future<span class="sc">$</span>y_true <span class="ot">&lt;-</span> data<span class="sc">$</span>Baccala_Mantecato</span>
<span id="cb153-2"><a href="#cb153-2" tabindex="-1"></a>forecast_future <span class="ot">&lt;-</span> forecast_future[,<span class="fu">c</span>(<span class="st">&quot;yhat&quot;</span>, <span class="st">&quot;ds&quot;</span>, <span class="st">&quot;y_true&quot;</span>)]</span>
<span id="cb153-3"><a href="#cb153-3" tabindex="-1"></a></span>
<span id="cb153-4"><a href="#cb153-4" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb153-5"><a href="#cb153-5" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> data<span class="sc">$</span>Date, <span class="at">y =</span> forecast_future<span class="sc">$</span>y_true, <span class="at">color =</span> <span class="st">&quot;Actual Values&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb153-6"><a href="#cb153-6" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> train<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">head</span>(forecast_future,<span class="dv">38</span>)<span class="sc">$</span>yhat, </span>
<span id="cb153-7"><a href="#cb153-7" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Fitted Values (Train)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb153-8"><a href="#cb153-8" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> test<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">tail</span>(forecast_future,<span class="dv">10</span>)<span class="sc">$</span>yhat, </span>
<span id="cb153-9"><a href="#cb153-9" tabindex="-1"></a>                <span class="at">color =</span>  <span class="st">&quot;Predicted Values (Test)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb153-10"><a href="#cb153-10" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span> <span class="ot">=</span> <span class="st">&quot;#FF7F7F&quot;</span>, </span>
<span id="cb153-11"><a href="#cb153-11" tabindex="-1"></a>                                <span class="st">&quot;Fitted Values (Train)&quot;</span> <span class="ot">=</span> <span class="st">&quot;#6BC3FF&quot;</span>, </span>
<span id="cb153-12"><a href="#cb153-12" tabindex="-1"></a>                                <span class="st">&quot;Predicted Values (Test)&quot;</span> <span class="ot">=</span> <span class="st">&quot;#8FBC8F&quot;</span>),</span>
<span id="cb153-13"><a href="#cb153-13" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span>, <span class="st">&quot;Fitted Values (Train)&quot;</span>, <span class="st">&quot;Predicted Values (Test)&quot;</span>)) <span class="sc">+</span></span>
<span id="cb153-14"><a href="#cb153-14" tabindex="-1"></a>  </span>
<span id="cb153-15"><a href="#cb153-15" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb153-16"><a href="#cb153-16" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Actual vs Fitted and Predicted Values for Baccala Mantecato (Prophet Model)&quot;</span>,</span>
<span id="cb153-17"><a href="#cb153-17" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb153-18"><a href="#cb153-18" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Value&quot;</span>,</span>
<span id="cb153-19"><a href="#cb153-19" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;Legend&quot;</span></span>
<span id="cb153-20"><a href="#cb153-20" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb153-21"><a href="#cb153-21" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb153-22"><a href="#cb153-22" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/prediction_plot_proph_m-1.png" width="768" /></p>
<p>We observed the same staff of other models, the mse value (we will
perfrom a final comparison between all the models) is high and looking
at the plot, we are not able to fit well the function under the
data.</p>
<div class="sourceCode" id="cb154"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="#cb154-1" tabindex="-1"></a>res_proph <span class="ot">&lt;-</span> train<span class="sc">$</span>Baccala_Mantecato <span class="sc">-</span> <span class="fu">head</span>(forecast_future<span class="sc">$</span>yhat, <span class="dv">38</span>)</span>
<span id="cb154-2"><a href="#cb154-2" tabindex="-1"></a>mse_train_prm <span class="ot">&lt;-</span> <span class="fu">mean</span>(res_proph<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb154-3"><a href="#cb154-3" tabindex="-1"></a><span class="co">#checkresiduals(res_proph)</span></span>
<span id="cb154-4"><a href="#cb154-4" tabindex="-1"></a><span class="fu">tsdisplay</span>(res_proph)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/resid_proph_m-1.png" width="768" /></p>
<div class="sourceCode" id="cb155"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" tabindex="-1"></a>aar1 <span class="ot">&lt;-</span> <span class="fu">Arima</span>(res_proph, <span class="at">order=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>))<span class="co"># didn&#39;t help--&gt;seasonal=list(order=c(0,1,0),period=12))</span></span>
<span id="cb155-2"><a href="#cb155-2" tabindex="-1"></a></span>
<span id="cb155-3"><a href="#cb155-3" tabindex="-1"></a>res_proph1 <span class="ot">&lt;-</span> train<span class="sc">$</span>Baccala_Mantecato <span class="sc">-</span> (<span class="fu">head</span>(forecast_future<span class="sc">$</span>yhat, <span class="dv">38</span>) <span class="sc">+</span> <span class="fu">fitted</span>(aar1))</span>
<span id="cb155-4"><a href="#cb155-4" tabindex="-1"></a>mse_train_prm1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(res_proph1<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb155-5"><a href="#cb155-5" tabindex="-1"></a>mse_train_prm1</span></code></pre></div>
<pre><code>## [1] 7.206331</code></pre>
<div class="sourceCode" id="cb157"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" tabindex="-1"></a><span class="co">#checkresiduals(res_proph)</span></span>
<span id="cb157-2"><a href="#cb157-2" tabindex="-1"></a><span class="fu">tsdisplay</span>(res_proph1)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/unnamed-chunk-1-1.png" width="768" /></p>
<div class="sourceCode" id="cb158"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="#cb158-1" tabindex="-1"></a><span class="fu">mean</span>((test<span class="sc">$</span>Baccala_Mantecato <span class="sc">-</span> (test_m<span class="sc">$</span>yhat <span class="sc">+</span> <span class="fu">as.numeric</span>(<span class="fu">forecast</span>(aar1, <span class="at">h=</span><span class="dv">10</span>)<span class="sc">$</span>mean)))<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 120.7406</code></pre>
</div>
<div id="baccala-vicentina-4" class="section level3">
<h3>Baccala Vicentina</h3>
<div class="sourceCode" id="cb160"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="#cb160-1" tabindex="-1"></a>proph_vd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb160-2"><a href="#cb160-2" tabindex="-1"></a>  <span class="at">ds =</span> train[,<span class="st">&quot;Date&quot;</span>],</span>
<span id="cb160-3"><a href="#cb160-3" tabindex="-1"></a>  <span class="at">y =</span> train[,<span class="st">&quot;Baccala_Vicentina&quot;</span>]</span>
<span id="cb160-4"><a href="#cb160-4" tabindex="-1"></a>)</span>
<span id="cb160-5"><a href="#cb160-5" tabindex="-1"></a><span class="fu">colnames</span>(proph_vd) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;ds&quot;</span>, <span class="st">&quot;y&quot;</span>)</span>
<span id="cb160-6"><a href="#cb160-6" tabindex="-1"></a>proph_vd<span class="sc">$</span>cap <span class="ot">&lt;-</span> <span class="fu">max</span>(proph_vd<span class="sc">$</span>y) <span class="sc">*</span> <span class="fl">1.1</span></span>
<span id="cb160-7"><a href="#cb160-7" tabindex="-1"></a><span class="fu">str</span>(proph_vd)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    38 obs. of  3 variables:
##  $ ds : Date, format: &quot;2021-01-01&quot; &quot;2021-02-01&quot; ...
##  $ y  : num  6.1 5.4 6.1 5.6 6.7 6 6.9 5.7 8.2 4.9 ...
##  $ cap: num  10.6 10.6 10.6 10.6 10.6 ...</code></pre>
<div class="sourceCode" id="cb162"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="#cb162-1" tabindex="-1"></a>proph_logistic<span class="ot">=</span><span class="fu">prophet</span>(proph_vd,  <span class="at">growth=</span><span class="st">&quot;logistic&quot;</span>, <span class="at">n.changepoints=</span><span class="dv">5</span>, </span>
<span id="cb162-2"><a href="#cb162-2" tabindex="-1"></a>           <span class="at">yearly.seasonality=</span><span class="cn">TRUE</span>, </span>
<span id="cb162-3"><a href="#cb162-3" tabindex="-1"></a>           <span class="at">seasonality.mode=</span><span class="st">&#39;multiplicative&#39;</span>)</span>
<span id="cb162-4"><a href="#cb162-4" tabindex="-1"></a></span>
<span id="cb162-5"><a href="#cb162-5" tabindex="-1"></a>proph_v<span class="ot">=</span><span class="fu">prophet</span>(proph_vd,  <span class="at">growth=</span><span class="st">&quot;linear&quot;</span>, <span class="at">n.changepoints=</span><span class="dv">5</span>, </span>
<span id="cb162-6"><a href="#cb162-6" tabindex="-1"></a>           <span class="at">yearly.seasonality=</span><span class="cn">TRUE</span>, </span>
<span id="cb162-7"><a href="#cb162-7" tabindex="-1"></a>           <span class="at">seasonality.mode=</span><span class="st">&#39;multiplicative&#39;</span>)</span>
<span id="cb162-8"><a href="#cb162-8" tabindex="-1"></a></span>
<span id="cb162-9"><a href="#cb162-9" tabindex="-1"></a>future_logistic <span class="ot">&lt;-</span> <span class="fu">make_future_dataframe</span>(proph_logistic, <span class="at">periods =</span> <span class="dv">10</span>, <span class="at">freq =</span> <span class="st">&quot;month&quot;</span>, <span class="at">include_history =</span> T)</span>
<span id="cb162-10"><a href="#cb162-10" tabindex="-1"></a>future_logistic<span class="sc">$</span>cap <span class="ot">&lt;-</span> <span class="fu">max</span>(proph_vd<span class="sc">$</span>y) <span class="sc">*</span> <span class="fl">1.1</span></span>
<span id="cb162-11"><a href="#cb162-11" tabindex="-1"></a>forecast_future_logistic <span class="ot">&lt;-</span> <span class="fu">predict</span>(proph_logistic, future_logistic)</span>
<span id="cb162-12"><a href="#cb162-12" tabindex="-1"></a>test_logistic <span class="ot">&lt;-</span> <span class="fu">tail</span>(forecast_future_logistic, <span class="dv">10</span>)</span>
<span id="cb162-13"><a href="#cb162-13" tabindex="-1"></a></span>
<span id="cb162-14"><a href="#cb162-14" tabindex="-1"></a><span class="fu">mean</span>((test<span class="sc">$</span>Baccala_Vicentina <span class="sc">-</span> test_logistic<span class="sc">$</span>yhat)<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 1.904377</code></pre>
<div class="sourceCode" id="cb164"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="#cb164-1" tabindex="-1"></a>future <span class="ot">&lt;-</span> <span class="fu">make_future_dataframe</span>(proph_v, <span class="at">periods =</span> <span class="dv">10</span>, <span class="at">freq =</span> <span class="st">&quot;month&quot;</span>, <span class="at">include_history =</span> T)</span>
<span id="cb164-2"><a href="#cb164-2" tabindex="-1"></a>future<span class="sc">$</span>cap <span class="ot">&lt;-</span> <span class="fu">max</span>(proph_vd<span class="sc">$</span>y) <span class="sc">*</span> <span class="fl">1.1</span></span>
<span id="cb164-3"><a href="#cb164-3" tabindex="-1"></a>forecast_future <span class="ot">&lt;-</span> <span class="fu">predict</span>(proph_v, future_logistic)</span>
<span id="cb164-4"><a href="#cb164-4" tabindex="-1"></a>test_v <span class="ot">&lt;-</span> <span class="fu">tail</span>(forecast_future, <span class="dv">10</span>)</span>
<span id="cb164-5"><a href="#cb164-5" tabindex="-1"></a></span>
<span id="cb164-6"><a href="#cb164-6" tabindex="-1"></a>mse_test_prv <span class="ot">&lt;-</span> <span class="fu">mean</span>((test<span class="sc">$</span>Baccala_Vicentina <span class="sc">-</span> test_v<span class="sc">$</span>yhat)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb164-7"><a href="#cb164-7" tabindex="-1"></a>mse_test_prv</span></code></pre></div>
<pre><code>## [1] 1.842281</code></pre>
<div class="sourceCode" id="cb166"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="#cb166-1" tabindex="-1"></a>forecast_future<span class="sc">$</span>y_true <span class="ot">&lt;-</span> data<span class="sc">$</span>Baccala_Vicentina</span>
<span id="cb166-2"><a href="#cb166-2" tabindex="-1"></a>forecast_future <span class="ot">&lt;-</span> forecast_future[,<span class="fu">c</span>(<span class="st">&quot;yhat&quot;</span>, <span class="st">&quot;ds&quot;</span>, <span class="st">&quot;y_true&quot;</span>)]</span>
<span id="cb166-3"><a href="#cb166-3" tabindex="-1"></a></span>
<span id="cb166-4"><a href="#cb166-4" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb166-5"><a href="#cb166-5" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> data<span class="sc">$</span>Date, <span class="at">y =</span> forecast_future<span class="sc">$</span>y_true, <span class="at">color =</span> <span class="st">&quot;Actual Values&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb166-6"><a href="#cb166-6" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> train<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">head</span>(forecast_future,<span class="dv">38</span>)<span class="sc">$</span>yhat, </span>
<span id="cb166-7"><a href="#cb166-7" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Fitted Values (Train)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb166-8"><a href="#cb166-8" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> test<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">tail</span>(forecast_future,<span class="dv">10</span>)<span class="sc">$</span>yhat, </span>
<span id="cb166-9"><a href="#cb166-9" tabindex="-1"></a>                <span class="at">color =</span>  <span class="st">&quot;Predicted Values (Test)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb166-10"><a href="#cb166-10" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span> <span class="ot">=</span> <span class="st">&quot;#FF7F7F&quot;</span>, </span>
<span id="cb166-11"><a href="#cb166-11" tabindex="-1"></a>                                <span class="st">&quot;Fitted Values (Train)&quot;</span> <span class="ot">=</span> <span class="st">&quot;#6BC3FF&quot;</span>, </span>
<span id="cb166-12"><a href="#cb166-12" tabindex="-1"></a>                                <span class="st">&quot;Predicted Values (Test)&quot;</span> <span class="ot">=</span> <span class="st">&quot;#8FBC8F&quot;</span>),</span>
<span id="cb166-13"><a href="#cb166-13" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Actual Values&quot;</span>, <span class="st">&quot;Fitted Values (Train)&quot;</span>, <span class="st">&quot;Predicted Values (Test)&quot;</span>)) <span class="sc">+</span></span>
<span id="cb166-14"><a href="#cb166-14" tabindex="-1"></a>  </span>
<span id="cb166-15"><a href="#cb166-15" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb166-16"><a href="#cb166-16" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Actual vs Fitted and Predicted Values for Baccala Vicentina (Prophet Model)&quot;</span>,</span>
<span id="cb166-17"><a href="#cb166-17" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb166-18"><a href="#cb166-18" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Value&quot;</span>,</span>
<span id="cb166-19"><a href="#cb166-19" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;Legend&quot;</span></span>
<span id="cb166-20"><a href="#cb166-20" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb166-21"><a href="#cb166-21" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb166-22"><a href="#cb166-22" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/prediction_plot_proph_v-1.png" width="768" /></p>
<div class="sourceCode" id="cb167"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="#cb167-1" tabindex="-1"></a>res_proph <span class="ot">&lt;-</span> train<span class="sc">$</span>Baccala_Vicentina <span class="sc">-</span> <span class="fu">head</span>(forecast_future<span class="sc">$</span>yhat, <span class="dv">38</span>)</span>
<span id="cb167-2"><a href="#cb167-2" tabindex="-1"></a>mse_train_prv <span class="ot">&lt;-</span> <span class="fu">mean</span>(res_proph<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb167-3"><a href="#cb167-3" tabindex="-1"></a><span class="fu">checkresiduals</span>(res_proph)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/resid_proph_v-1.png" width="768" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals
## Q* = 27.881, df = 8, p-value = 0.0004975
## 
## Model df: 0.   Total lags used: 8</code></pre>
</div>
</div>
<div id="exponential-smoothing-model" class="section level2">
<h2>Exponential Smoothing Model</h2>
<p>We decide to try also an exponential smoothing model.</p>
<div id="baccala-mantecato-4" class="section level3">
<h3>Baccala Mantecato</h3>
<p>First we initialize a data frame to store the results of the models
that we are going to test</p>
<div class="sourceCode" id="cb169"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="#cb169-1" tabindex="-1"></a>results_m <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb169-2"><a href="#cb169-2" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">character</span>(),</span>
<span id="cb169-3"><a href="#cb169-3" tabindex="-1"></a>  <span class="at">MSE =</span> <span class="fu">numeric</span>(),</span>
<span id="cb169-4"><a href="#cb169-4" tabindex="-1"></a>  <span class="at">AIC =</span> <span class="fu">numeric</span>(),</span>
<span id="cb169-5"><a href="#cb169-5" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span></span>
<span id="cb169-6"><a href="#cb169-6" tabindex="-1"></a>)</span>
<span id="cb169-7"><a href="#cb169-7" tabindex="-1"></a><span class="co"># Create the time series object for training</span></span>
<span id="cb169-8"><a href="#cb169-8" tabindex="-1"></a>train_series_m <span class="ot">&lt;-</span> <span class="fu">ts</span>(train<span class="sc">$</span>Baccala_Mantecato, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">2021</span>, <span class="dv">1</span>), <span class="at">frequency =</span> <span class="dv">12</span>)</span></code></pre></div>
<div id="ets-model" class="section level4">
<h4>ETS Model</h4>
<p>First we try the classic ETS model</p>
<div class="sourceCode" id="cb170"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="#cb170-1" tabindex="-1"></a>fit_ES_m <span class="ot">&lt;-</span> <span class="fu">ets</span>(train_series_m)</span></code></pre></div>
<p>The ets() function fits an exponential smoothing model, automatically
selecting the best configuration based on the data.</p>
<div class="sourceCode" id="cb171"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="#cb171-1" tabindex="-1"></a>forecast_ES_m <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit_ES_m, <span class="at">h =</span> <span class="fu">length</span>(y_testm))</span>
<span id="cb171-2"><a href="#cb171-2" tabindex="-1"></a>mse_ets_m <span class="ot">&lt;-</span> <span class="fu">mse</span>(forecast_ES_m<span class="sc">$</span>mean,  y_testm)</span>
<span id="cb171-3"><a href="#cb171-3" tabindex="-1"></a>mse_ets_m_train <span class="ot">&lt;-</span> <span class="fu">mse</span>(<span class="fu">fitted</span>(fit_ES_m), train<span class="sc">$</span>Baccala_Mantecato)</span>
<span id="cb171-4"><a href="#cb171-4" tabindex="-1"></a>aic_ets_m <span class="ot">&lt;-</span> <span class="fu">AIC</span>(fit_ES_m)</span>
<span id="cb171-5"><a href="#cb171-5" tabindex="-1"></a>results_m <span class="ot">&lt;-</span> <span class="fu">rbind</span>(results_m, <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="st">&quot;ETS&quot;</span>, <span class="at">MSE =</span> mse_ets_m, <span class="at">AIC =</span> aic_ets_m))</span></code></pre></div>
<p>We obtained a MSE of 111.7995 and an AIC of 266.4093 wich are good
results. So we decided to try to use the ETS model also with additive
and multiplicative seasonality to see if we can improve the results
obtained with the classic ETS model.</p>
</div>
<div id="holt-winters-additive-seasonality-via-ets"
class="section level4">
<h4>Holt-Winters Additive Seasonality (via ETS)</h4>
<div class="sourceCode" id="cb172"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="#cb172-1" tabindex="-1"></a>fit_hw_add_m <span class="ot">&lt;-</span> <span class="fu">ets</span>(train_series_m, <span class="at">model =</span> <span class="st">&quot;AAA&quot;</span>)</span>
<span id="cb172-2"><a href="#cb172-2" tabindex="-1"></a>forecast_hw_add_m <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit_hw_add_m, <span class="at">h =</span> <span class="fu">length</span>(y_testm))</span>
<span id="cb172-3"><a href="#cb172-3" tabindex="-1"></a>mse_hw_add_m <span class="ot">&lt;-</span> <span class="fu">mse</span>(forecast_hw_add_m<span class="sc">$</span>mean, y_testm)</span>
<span id="cb172-4"><a href="#cb172-4" tabindex="-1"></a>aic_hw_add_m <span class="ot">&lt;-</span> <span class="fu">AIC</span>(fit_hw_add_m)</span>
<span id="cb172-5"><a href="#cb172-5" tabindex="-1"></a>results_m <span class="ot">&lt;-</span> <span class="fu">rbind</span>(results_m, <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="st">&quot;Holt-Winters Additive&quot;</span>, <span class="at">MSE =</span> mse_hw_add_m, <span class="at">AIC =</span> aic_hw_add_m))</span></code></pre></div>
<p>The results are worse than the ETS model, with a MSE of 114.8030 and
an AIC of 274.4056.</p>
</div>
<div id="holt-winters-multiplicative-seasonality-via-ets"
class="section level4">
<h4>Holt-Winters Multiplicative Seasonality (via ETS)</h4>
<div class="sourceCode" id="cb173"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="#cb173-1" tabindex="-1"></a>fit_hw_mult_m <span class="ot">&lt;-</span> <span class="fu">ets</span>(train_series_m, <span class="at">model =</span> <span class="st">&quot;MAM&quot;</span>)</span>
<span id="cb173-2"><a href="#cb173-2" tabindex="-1"></a>forecast_hw_mult_m <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit_hw_mult_m, <span class="at">h =</span> <span class="fu">length</span>(y_testm))</span>
<span id="cb173-3"><a href="#cb173-3" tabindex="-1"></a>mse_hw_mult_m <span class="ot">&lt;-</span> <span class="fu">mse</span>(forecast_hw_mult_m<span class="sc">$</span>mean, y_testm)</span>
<span id="cb173-4"><a href="#cb173-4" tabindex="-1"></a>aic_hw_mult_m <span class="ot">&lt;-</span> <span class="fu">AIC</span>(fit_hw_mult_m)</span>
<span id="cb173-5"><a href="#cb173-5" tabindex="-1"></a>results_m <span class="ot">&lt;-</span> <span class="fu">rbind</span>(results_m, <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="st">&quot;Holt-Winters Multiplicative&quot;</span>, <span class="at">MSE =</span> mse_hw_mult_m, <span class="at">AIC =</span> aic_hw_mult_m))</span></code></pre></div>
<p>It’’s appening the same as before, the results are worse than the ETS
model, with a MSE of 177.2098 and an AIC of 274.7737.</p>
<div class="sourceCode" id="cb174"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="#cb174-1" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb174-2"><a href="#cb174-2" tabindex="-1"></a><span class="fu">print</span>(results_m)</span></code></pre></div>
<pre><code>##                         Model      MSE      AIC
## 1                         ETS 111.7995 266.4093
## 2       Holt-Winters Additive 114.8030 274.4056
## 3 Holt-Winters Multiplicative 177.2098 274.7737</code></pre>
<p>So as we can see from the table the best model for the Baccala
Mantecato series is the ETS model, inlcuding additive and multiplicative
seasonality doesn’t improve the results obtained with the classic ETS
model so we decide to keep the one with the lowest MSE.</p>
<div class="sourceCode" id="cb176"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="#cb176-1" tabindex="-1"></a><span class="fu">tsdisplay</span>(<span class="fu">residuals</span>(fit_ES_m), <span class="at">main =</span> <span class="st">&quot;Residuals of ETS Model&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/resid_ETS_M-1.png" width="768" />
The residuals of the ETS model seems randomly scattered around 0,
without any visible pattern. This indicates that the model has
appropriately captured the underlying trends in the data. However, there
are some peaks and dips in the residuals that might suggest minor
variations not captured by the model. As also the not so low MSE
suggests, the model is not perfect but it is the best we can get.</p>
<p>The ACF and PACF of the residuals reveal whether the residuals are
uncorrelated and resemble white noise. In this case, most lags fall
within the confidence intervals, indicating that the residuals exhibit
minimal autocorrelation. This is a good sign as it suggests the ETS
model is adequately modeling the data without leaving behind systematic
errors.</p>
<p>Finally we plot the predicted values and the actual ones.</p>
<div class="sourceCode" id="cb177"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="#cb177-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb177-2"><a href="#cb177-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> data<span class="sc">$</span>Date, <span class="at">y =</span> data<span class="sc">$</span>Baccala_Mantecato, <span class="at">color =</span> <span class="st">&quot;Actual Values&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb177-3"><a href="#cb177-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> train<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">fitted</span>(fit_ES_m), <span class="at">color =</span> <span class="st">&quot;Train Fitted Values (ETS)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb177-4"><a href="#cb177-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> test<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">forecast</span>(fit_ES_m, <span class="at">h =</span> <span class="fu">nrow</span>(test))<span class="sc">$</span>mean, </span>
<span id="cb177-5"><a href="#cb177-5" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Test Predicted Values (ETS)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb177-6"><a href="#cb177-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb177-7"><a href="#cb177-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Time Series: Actual vs Predicted Values - Baccalà Mantecato</span><span class="sc">\n</span><span class="st">ETS Model&quot;</span>,</span>
<span id="cb177-8"><a href="#cb177-8" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb177-9"><a href="#cb177-9" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Value&quot;</span>,</span>
<span id="cb177-10"><a href="#cb177-10" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;Legend&quot;</span></span>
<span id="cb177-11"><a href="#cb177-11" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb177-12"><a href="#cb177-12" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb177-13"><a href="#cb177-13" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>, <span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/plot_ES_m-1.png" width="768" />
As we can see from the plot the blue line representing the fitted values
during the training phase closely follows the red line of actual values,
which indicates that the ETS model is performing well in capturing the
data’’s behavior during training. The Exponential Smoothing model is
able to capture the underlying trends in the data,the predicted values
(Green Line) are close to the actual ones, and the model seems to be a
good fit for the data, though it shows some deviation during more
extreme values.</p>
</div>
</div>
<div id="baccala-vicentina-5" class="section level3">
<h3>Baccala Vicentina</h3>
<p>Now we do the same also for the Baccala Vicentina series</p>
<div class="sourceCode" id="cb178"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="#cb178-1" tabindex="-1"></a>results_v <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb178-2"><a href="#cb178-2" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">character</span>(),</span>
<span id="cb178-3"><a href="#cb178-3" tabindex="-1"></a>  <span class="at">MSE =</span> <span class="fu">numeric</span>(),</span>
<span id="cb178-4"><a href="#cb178-4" tabindex="-1"></a>  <span class="at">AIC =</span> <span class="fu">numeric</span>(),</span>
<span id="cb178-5"><a href="#cb178-5" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span></span>
<span id="cb178-6"><a href="#cb178-6" tabindex="-1"></a>)</span>
<span id="cb178-7"><a href="#cb178-7" tabindex="-1"></a></span>
<span id="cb178-8"><a href="#cb178-8" tabindex="-1"></a>train_series_v <span class="ot">&lt;-</span> <span class="fu">ts</span>(train<span class="sc">$</span>Baccala_Vicentina, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">2021</span>, <span class="dv">1</span>), <span class="at">frequency =</span> <span class="dv">12</span>)</span></code></pre></div>
<div id="ets-model-1" class="section level4">
<h4>ETS Model</h4>
<div class="sourceCode" id="cb179"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="#cb179-1" tabindex="-1"></a>fit_ES_v <span class="ot">&lt;-</span> <span class="fu">ets</span>(train_series_v)</span>
<span id="cb179-2"><a href="#cb179-2" tabindex="-1"></a>forecast_ES_v <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit_ES_v, <span class="at">h =</span> <span class="fu">length</span>(y_testv))</span>
<span id="cb179-3"><a href="#cb179-3" tabindex="-1"></a>mse_ets_v <span class="ot">&lt;-</span> <span class="fu">mse</span>(forecast_ES_v<span class="sc">$</span>mean, y_testv)</span>
<span id="cb179-4"><a href="#cb179-4" tabindex="-1"></a>aic_ets_v <span class="ot">&lt;-</span> <span class="fu">AIC</span>(fit_ES_v)</span>
<span id="cb179-5"><a href="#cb179-5" tabindex="-1"></a>results_v <span class="ot">&lt;-</span> <span class="fu">rbind</span>(results_v, <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="st">&quot;ETS&quot;</span>, <span class="at">MSE =</span> mse_ets_v, <span class="at">AIC =</span> aic_ets_v))</span></code></pre></div>
<p>With the initial exponential smoothing model we obtained a really
good MSE of 1.475781 and an AIC of 105.6035, and these are already good
results. However, we also try the ETS model with additive and
multiplicative seasonality to see if we can improve the already
results.</p>
</div>
<div id="holt-winters-additive-seasonality-via-ets-1"
class="section level4">
<h4>Holt-Winters Additive Seasonality (via ETS)</h4>
<div class="sourceCode" id="cb180"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="#cb180-1" tabindex="-1"></a>fit_hw_add_v <span class="ot">&lt;-</span> <span class="fu">ets</span>(train_series_v, <span class="at">model =</span> <span class="st">&quot;AAA&quot;</span>)</span>
<span id="cb180-2"><a href="#cb180-2" tabindex="-1"></a>forecast_hw_add_v <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit_hw_add_v, <span class="at">h =</span> <span class="fu">length</span>(y_testv))</span>
<span id="cb180-3"><a href="#cb180-3" tabindex="-1"></a>mse_hw_add_v <span class="ot">&lt;-</span> <span class="fu">mse</span>(forecast_hw_add_v<span class="sc">$</span>mean, y_testv)</span>
<span id="cb180-4"><a href="#cb180-4" tabindex="-1"></a>aic_hw_add_v <span class="ot">&lt;-</span> <span class="fu">AIC</span>(fit_hw_add_v)</span>
<span id="cb180-5"><a href="#cb180-5" tabindex="-1"></a>results_v <span class="ot">&lt;-</span> <span class="fu">rbind</span>(results_v, <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="st">&quot;Holt-Winters Additive&quot;</span>, <span class="at">MSE =</span> mse_hw_add_v, <span class="at">AIC =</span> aic_hw_add_v))</span></code></pre></div>
<p>Including additive seasonality doesn’t improve the results obtained
with the classic ETS model, since the MSE is 1.512441 and the AIC is
111.4078.</p>
</div>
<div id="holt-winters-multiplicative-seasonality-via-ets-1"
class="section level4">
<h4>Holt-Winters Multiplicative Seasonality (via ETS)</h4>
<div class="sourceCode" id="cb181"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="#cb181-1" tabindex="-1"></a>fit_hw_mult_v <span class="ot">&lt;-</span> <span class="fu">ets</span>(train_series_v, <span class="at">model =</span> <span class="st">&quot;MAM&quot;</span>)</span>
<span id="cb181-2"><a href="#cb181-2" tabindex="-1"></a>forecast_hw_mult_v <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit_hw_mult_v, <span class="at">h =</span> <span class="fu">length</span>(y_testv))</span>
<span id="cb181-3"><a href="#cb181-3" tabindex="-1"></a>mse_hw_mult_v <span class="ot">&lt;-</span> <span class="fu">mse</span>(forecast_hw_mult_v<span class="sc">$</span>mean, y_testv)</span>
<span id="cb181-4"><a href="#cb181-4" tabindex="-1"></a>mse_hw_mult_v_train <span class="ot">&lt;-</span> <span class="fu">mse</span>(<span class="fu">fitted</span>(fit_hw_mult_v), train<span class="sc">$</span>Baccala_Vicentina)</span>
<span id="cb181-5"><a href="#cb181-5" tabindex="-1"></a>aic_hw_mult_v <span class="ot">&lt;-</span> <span class="fu">AIC</span>(fit_hw_mult_v)</span>
<span id="cb181-6"><a href="#cb181-6" tabindex="-1"></a>results_v <span class="ot">&lt;-</span> <span class="fu">rbind</span>(results_v, <span class="fu">data.frame</span>(<span class="at">Model =</span> <span class="st">&quot;Holt-Winters Multiplicative&quot;</span>, <span class="at">MSE =</span> mse_hw_mult_v, <span class="at">AIC =</span> aic_hw_mult_v))</span></code></pre></div>
<p>Including multiplicative seasonality instead, slightly improve the
obtained MSE reducing it to 1.434768, on the other hand it increases the
AIC to 109.9921.</p>
<div class="sourceCode" id="cb182"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="#cb182-1" tabindex="-1"></a><span class="fu">print</span>(results_v)</span></code></pre></div>
<pre><code>##                         Model      MSE      AIC
## 1                         ETS 1.475781 105.6035
## 2       Holt-Winters Additive 1.512441 111.4078
## 3 Holt-Winters Multiplicative 1.434768 109.9921</code></pre>
<p>Since our goal is to minimize the MSE, we decide to keep the
Holt-Winters with multiplicative seasonality which has the lowest MSE
among the three models.</p>
<div class="sourceCode" id="cb184"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="#cb184-1" tabindex="-1"></a><span class="fu">tsdisplay</span>(<span class="fu">residuals</span>(fit_hw_mult_v), <span class="at">main =</span> <span class="st">&quot;Residuals of Holt-Winters Multiplicative Seasonality Model&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/resid_HWM_V-1.png" width="768" /></p>
<p>The residuals plot for the Holt-Winters Multiplicative Seasonality
Model shows that the residuals are randomly distributed around zero,
which is an indication of a good fit. The residuals do not exhibit any
apparent pattern or seasonality, which means the model has effectively
accounted for the multiplicative seasonal variations in the data.</p>
<p>The ACF and PACF for the residuals further confirm the randomness of
the residuals. There are no significant spikes outside the confidence
bands, suggesting that the residuals are uncorrelated and approximate
white noise. This validates the model’’s performance and confirms that
it has captured the key elements of the time series.</p>
<div class="sourceCode" id="cb185"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="#cb185-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb185-2"><a href="#cb185-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> data<span class="sc">$</span>Date, <span class="at">y =</span> data<span class="sc">$</span>Baccala_Vicentina, <span class="at">color =</span> <span class="st">&quot;Actual Values&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb185-3"><a href="#cb185-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> train<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">fitted</span>(fit_hw_mult_v ), <span class="at">color =</span> <span class="st">&quot;Train Fitted Values (HWMS)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb185-4"><a href="#cb185-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> test<span class="sc">$</span>Date, <span class="at">y =</span> <span class="fu">forecast</span>(fit_hw_mult_v , <span class="at">h =</span> <span class="fu">nrow</span>(test))<span class="sc">$</span>mean, </span>
<span id="cb185-5"><a href="#cb185-5" tabindex="-1"></a>                <span class="at">color =</span> <span class="st">&quot;Test Predicted Values (HWMS)&quot;</span>), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb185-6"><a href="#cb185-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb185-7"><a href="#cb185-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Time Series: Actual vs Predicted Values - Baccalà Vicentina</span><span class="sc">\n</span><span class="st">Holt-Winters Multiplicative Seasonality Model&quot;</span>,</span>
<span id="cb185-8"><a href="#cb185-8" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb185-9"><a href="#cb185-9" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Value&quot;</span>,</span>
<span id="cb185-10"><a href="#cb185-10" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;Legend&quot;</span></span>
<span id="cb185-11"><a href="#cb185-11" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb185-12"><a href="#cb185-12" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb185-13"><a href="#cb185-13" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>, <span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>))</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/plot_HWM_V-1.png" width="768" />
Looking to the plot we can see that the fitted values during the
training period are well aligned with the actual values, demonstrating
that the Holt-Winters model effectively captures the multiplicative
seasonal behavior of the time series. However, the model’s performance
slightly deteriorates during the peaks and troughs, which is expected
for such models.</p>
<p>In the test period, the green line representing the predicted values
shows a good alignment with the actual values, maintaining the seasonal
structure. Some underestimations occur during sharp spikes in the data,
but overall, the model provides reliable forecasts.</p>
</div>
</div>
</div>
</div>
<div id="results" class="section level1">
<h1>Results</h1>
<div class="sourceCode" id="cb186"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="#cb186-1" tabindex="-1"></a>name_models <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Linear Regression&quot;</span>, <span class="st">&quot;SARIMA&quot;</span>, <span class="st">&quot;Prophet&quot;</span>, <span class="st">&quot;SARIMAX&quot;</span>, <span class="st">&quot;Exponential Smoothing&quot;</span>)</span>
<span id="cb186-2"><a href="#cb186-2" tabindex="-1"></a></span>
<span id="cb186-3"><a href="#cb186-3" tabindex="-1"></a>mse_train_m <span class="ot">&lt;-</span> <span class="fu">c</span>(mse_train_lrm, mse_train_sarimam, mse_train_prm, mse_train_sarimaxm, mse_ets_m_train)</span>
<span id="cb186-4"><a href="#cb186-4" tabindex="-1"></a>mse_train_v <span class="ot">&lt;-</span> <span class="fu">c</span>(mse_train_lrv, mse_train_sarimav, mse_train_prv, mse_train_sarimaxv, mse_hw_mult_v_train)</span>
<span id="cb186-5"><a href="#cb186-5" tabindex="-1"></a></span>
<span id="cb186-6"><a href="#cb186-6" tabindex="-1"></a>mse_test_m <span class="ot">&lt;-</span> <span class="fu">c</span>(mse_test_lrm, mse_test_sarimam, mse_test_prm, mse_test_sarimaxm, mse_ets_m)</span>
<span id="cb186-7"><a href="#cb186-7" tabindex="-1"></a>mse_test_v <span class="ot">&lt;-</span> <span class="fu">c</span>(mse_test_lrv, mse_test_sarimav, mse_test_prv, mse_test_sarimaxv, mse_hw_mult_v)</span>
<span id="cb186-8"><a href="#cb186-8" tabindex="-1"></a></span>
<span id="cb186-9"><a href="#cb186-9" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb186-10"><a href="#cb186-10" tabindex="-1"></a>  <span class="at">Model =</span> name_models,</span>
<span id="cb186-11"><a href="#cb186-11" tabindex="-1"></a>  </span>
<span id="cb186-12"><a href="#cb186-12" tabindex="-1"></a>  <span class="at">MSE_Train_M =</span> mse_train_m,</span>
<span id="cb186-13"><a href="#cb186-13" tabindex="-1"></a>  <span class="at">MSE_Train_V =</span> mse_train_v,</span>
<span id="cb186-14"><a href="#cb186-14" tabindex="-1"></a>  </span>
<span id="cb186-15"><a href="#cb186-15" tabindex="-1"></a>  <span class="at">MSE_Test_M =</span> mse_test_m,</span>
<span id="cb186-16"><a href="#cb186-16" tabindex="-1"></a>  <span class="at">MSE_Test_V =</span> mse_test_v</span>
<span id="cb186-17"><a href="#cb186-17" tabindex="-1"></a>)</span>
<span id="cb186-18"><a href="#cb186-18" tabindex="-1"></a><span class="fu">kable</span>(results, <span class="at">caption =</span> <span class="st">&quot;Results of the models on the training and test sets&quot;</span>)</span></code></pre></div>
<table>
<caption>Results of the models on the training and test sets</caption>
<colgroup>
<col width="32%" />
<col width="17%" />
<col width="17%" />
<col width="16%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Model</th>
<th align="right">MSE_Train_M</th>
<th align="right">MSE_Train_V</th>
<th align="right">MSE_Test_M</th>
<th align="right">MSE_Test_V</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Linear Regression</td>
<td align="right">6.775488</td>
<td align="right">0.1879386</td>
<td align="right">45.59531</td>
<td align="right">1.512444</td>
</tr>
<tr class="even">
<td align="left">SARIMA</td>
<td align="right">29.757929</td>
<td align="right">0.3605396</td>
<td align="right">104.50500</td>
<td align="right">2.265000</td>
</tr>
<tr class="odd">
<td align="left">Prophet</td>
<td align="right">9.229036</td>
<td align="right">0.1129688</td>
<td align="right">119.07301</td>
<td align="right">1.842281</td>
</tr>
<tr class="even">
<td align="left">SARIMAX</td>
<td align="right">14.297317</td>
<td align="right">0.3683188</td>
<td align="right">64.05571</td>
<td align="right">2.349442</td>
</tr>
<tr class="odd">
<td align="left">Exponential Smoothing</td>
<td align="right">13.246196</td>
<td align="right">0.1936225</td>
<td align="right">111.79945</td>
<td align="right">1.434768</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb187"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="#cb187-1" tabindex="-1"></a><span class="fu">plot_results</span>(results, <span class="st">&quot;MSE_Train_M&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/plot_results-1.png" width="768" /></p>
<div class="sourceCode" id="cb188"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="#cb188-1" tabindex="-1"></a><span class="fu">plot_results</span>(results, <span class="st">&quot;MSE_Test_M&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/plot_results-2.png" width="768" /></p>
<div class="sourceCode" id="cb189"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="#cb189-1" tabindex="-1"></a><span class="fu">plot_results</span>(results, <span class="st">&quot;MSE_Train_V&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/plot_results-3.png" width="768" /></p>
<div class="sourceCode" id="cb190"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="#cb190-1" tabindex="-1"></a><span class="fu">plot_results</span>(results, <span class="st">&quot;MSE_Test_V&quot;</span>)</span></code></pre></div>
<p><img src="FINAL_CODE_NEW_files/figure-html/plot_results-4.png" width="768" /></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
